include("${CPKT_SOURCE}/cmake/extract-release-archive.cmake")
include("${CPKT_SOURCE}/cmake/CpktSDKValidate.cmake")
include("${CPKT_SOURCE}/cmake/package_inspection.cmake")
include("${CPKT_SOURCE}/tests/privacy_scan.cmake")
cpkt_extract_release_archive("${CPKT_ARCHIVE}" "${CPKT_PREFIX}"
  "cpkt-${CPKT_VERSION}-${CPKT_TARGET}" TRUE)
set(CPKT_TARGET_ID "${CPKT_TARGET}")
set(CPKT_EXPECTED_VERSION "${CPKT_VERSION}")
_cpkt_sdk_validate_prefix("${CPKT_PREFIX}" core)
get_property(owned GLOBAL PROPERTY "CPKT_PAYLOAD_PATHS_${_cpkt_sdk_key}")
file(GLOB_RECURSE files LIST_DIRECTORIES FALSE RELATIVE "${CPKT_PREFIX}" "${CPKT_PREFIX}/*")
list(SORT files)
list(SORT owned)
if(NOT files STREQUAL owned)
  message(FATAL_ERROR "Archive payload differs from its manifest inventory")
endif()
set(CPKT_ROOT "${CPKT_SOURCE}")
cpkt_assert_tree_has_no_private_traces("${CPKT_PREFIX}" "SDK")
if(CPKT_TARGET MATCHES "^aarch64")
  set(machine AArch64)
elseif(CPKT_TARGET MATCHES "^armhf")
  set(machine ARM)
else()
  set(machine "(X86-64|x86-64)")
endif()
foreach(relative IN LISTS files)
  set(file "${CPKT_PREFIX}/${relative}")
  if(IS_SYMLINK "${file}")
    continue()
  endif()
  file(STRINGS "${file}" private_traces REGEX "/home/|/Users/|/private/tmp/|\\.cache/cpkt/|libpslog")
  if(private_traces)
    message(FATAL_ERROR "Private or test-only payload in ${relative}")
  endif()
  file(READ "${file}" magic LIMIT 4 HEX)
  if(magic STREQUAL "7f454c46" OR (CPKT_TARGET MATCHES "-linux-" AND relative MATCHES "\\.a$"))
    execute_process(COMMAND "${CPKT_TOOL}" -h "${file}"
      RESULT_VARIABLE result OUTPUT_VARIABLE header ERROR_VARIABLE error)
    string(REGEX MATCHALL "Machine:[^\n]+" machines "${header}")
    if(NOT result EQUAL 0 OR NOT machines)
      message(FATAL_ERROR "Wrong ELF architecture: ${relative}\n${error}")
    endif()
    foreach(actual_machine IN LISTS machines)
      if(NOT actual_machine MATCHES "${machine}")
        message(FATAL_ERROR "Wrong ELF archive member architecture: ${relative}: ${actual_machine}")
      endif()
    endforeach()
    set(CPKT_READELF "${CPKT_TOOL}")
    if(magic STREQUAL "7f454c46")
      cpkt_assert_elf_runtime_metadata_file_relocatable("${file}" "${relative}")
    endif()
  elseif(CPKT_TARGET MATCHES "darwin$" AND magic STREQUAL "cffaedfe")
    execute_process(COMMAND "${CPKT_TOOL}" -hv "${file}" RESULT_VARIABLE result OUTPUT_VARIABLE header)
    if(NOT result EQUAL 0 OR NOT header MATCHES "ARM64")
      message(FATAL_ERROR "Wrong Mach-O architecture: ${relative}")
    endif()
    set(CPKT_OTOOL "${CPKT_TOOL}")
    cpkt_assert_darwin_dylib_relocatable("${file}" "${relative}")
    cpkt_assert_darwin_deployment_target("${file}" "15.0" "${relative}")
  endif()
endforeach()
