# The smoke ZIP is flat and contains regular files only. Validate types and
# exact names before native extraction; it is not a general archive interface.
include("${CPKT_SOURCE}/cmake/package_inspection.cmake")
include("${CPKT_SOURCE}/cmake/CpktMutationPaths.cmake")
include("${CPKT_SOURCE}/tests/test-command.cmake")
include("${CPKT_SOURCE}/tests/privacy_scan.cmake")
cpkt_test_command("${CMAKE_COMMAND}" -E tar tf "${CPKT_SMOKE_ARCHIVE}")
string(REPLACE "\n" ";" members "${CPKT_TEST_OUTPUT}")
list(FILTER members EXCLUDE REGEX "^$")
set(expected darwin-smoke-test/ darwin-smoke-test/bin/ darwin-smoke-test/lib/
  darwin-smoke-test/bin/cpkt_abi_smoke_static darwin-smoke-test/bin/cpkt_abi_smoke_shared
  darwin-smoke-test/packages.json)
file(GLOB libraries RELATIVE "${CPKT_PREFIX}/lib" "${CPKT_PREFIX}/lib/*.dylib")
foreach(name IN LISTS libraries)
  list(APPEND expected "darwin-smoke-test/lib/${name}")
endforeach()
list(SORT members)
list(SORT expected)
if(NOT members STREQUAL expected)
  message(FATAL_ERROR "Darwin smoke ZIP has an unexpected or incomplete inventory")
endif()
cpkt_test_command("${CMAKE_COMMAND}" -E tar tvf "${CPKT_SMOKE_ARCHIVE}")
string(REPLACE "\n" ";" records "${CPKT_TEST_OUTPUT}")
foreach(record IN LISTS records)
  if(record STREQUAL "")
    continue()
  endif()
  if(record MATCHES " darwin-smoke-test/(bin/|lib/)?$")
    set(mode drwxr-xr-x)
  elseif(record MATCHES " darwin-smoke-test/bin/[^/]+$")
    set(mode -rwxr-xr-x)
  else()
    set(mode -rw-r--r--)
  endif()
  string(FIND "${record}" "${mode}" found)
  if(NOT found EQUAL 0)
    message(FATAL_ERROR "Darwin smoke ZIP has an unsupported entry type or mode: ${record}")
  endif()
endforeach()
set(work "${CPKT_WORK}/smoke")
cpkt_validate_mutation_paths("${work}")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}")
file(ARCHIVE_EXTRACT INPUT "${CPKT_SMOKE_ARCHIVE}" DESTINATION "${work}")
set(root "${work}/darwin-smoke-test")
file(READ "${root}/packages.json" packages)
file(READ "${CPKT_PREFIX}/share/cpkt/packages/core.json" manifest)
string(JSON id GET "${packages}" core)
string(JSON expected_id GET "${manifest}" package_id)
if(NOT id STREQUAL expected_id)
  message(FATAL_ERROR "Darwin smoke ZIP belongs to a different SDK")
endif()
foreach(name IN LISTS libraries)
  file(SHA256 "${CPKT_PREFIX}/lib/${name}" expected_hash)
  file(SHA256 "${root}/lib/${name}" actual_hash)
  if(NOT actual_hash STREQUAL expected_hash)
    message(FATAL_ERROR "Darwin smoke library differs from the SDK: ${name}")
  endif()
endforeach()
set(CPKT_OTOOL "${CPKT_TOOL}")
foreach(name cpkt_abi_smoke_static cpkt_abi_smoke_shared)
  set(binary "${root}/bin/${name}")
  cpkt_test_command("${CPKT_TOOL}" -hv "${binary}")
  if(NOT CPKT_TEST_OUTPUT MATCHES "ARM64" OR NOT CPKT_TEST_OUTPUT MATCHES "EXECUTE")
    message(FATAL_ERROR "Darwin smoke executable has the wrong architecture or type: ${name}")
  endif()
  cpkt_assert_darwin_dylib_relocatable("${binary}" "${name}")
  cpkt_assert_darwin_deployment_target("${binary}" "15.0" "${name}")
endforeach()
set(CPKT_ROOT "${CPKT_SOURCE}")
cpkt_assert_tree_has_no_private_traces("${root}" "Darwin smoke ZIP")
