if(MODE STREQUAL "build-shared")
  file(APPEND "${ROOT}/events" "shared build begin\n")
  foreach(attempt RANGE 1 100)
    if(EXISTS "${ROOT}/static-active")
      file(WRITE "${ROOT}/shared-ready" "ready")
      file(APPEND "${ROOT}/events" "shared build end\n")
      return()
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.05)
  endforeach()
  message(FATAL_ERROR "Shared build did not overlap static install")
elseif(MODE STREQUAL "install-static")
  file(APPEND "${ROOT}/events" "static install begin\n")
  file(WRITE "${ROOT}/static-active" "active")
  foreach(attempt RANGE 1 100)
    if(EXISTS "${ROOT}/shared-ready")
      execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.2)
      file(WRITE "${ROOT}/config" "shared-pending")
      file(REMOVE "${ROOT}/static-active")
      file(APPEND "${ROOT}/events" "static install end\n")
      return()
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.05)
  endforeach()
  message(FATAL_ERROR "Variant builds were serialized unnecessarily")
elseif(MODE STREQUAL "install-shared")
  file(APPEND "${ROOT}/events" "shared install begin\n")
  if(EXISTS "${ROOT}/static-active")
    message(FATAL_ERROR "Concurrent common-prefix installs")
  endif()
  file(WRITE "${ROOT}/config" "shared")
  file(APPEND "${ROOT}/events" "shared install end\n")
endif()
