file(READ "${CPKT_INPUT}" inventory)
set(fields missing_c89_facade_functions)
if(CPKT_KIND STREQUAL "openssl")
  list(APPEND fields unclassified_dynamic_functions unclassified_abi_exports)
elseif(CPKT_KIND MATCHES "^(nghttp2|libssh2)$")
  list(APPEND fields missing_native_declarations)
elseif(CPKT_KIND STREQUAL "mqttc")
  list(APPEND fields missing_dynamic_definitions)
elseif(CPKT_KIND STREQUAL "lua")
  list(APPEND fields missing_dynamic_definitions missing_convenience_equivalents private_native_imports)
else()
  message(FATAL_ERROR "Unknown API inventory: ${CPKT_KIND}")
endif()
foreach(field IN LISTS fields)
  string(JSON count LENGTH "${inventory}" "${field}")
  if(NOT count EQUAL 0)
    string(JSON entries GET "${inventory}" "${field}")
    message(FATAL_ERROR "API contract failed: ${field}: ${entries}")
  endif()
endforeach()
if(CPKT_KIND STREQUAL "lua")
  string(JSON count GET "${inventory}" native_public_function_count)
  string(JSON declared GET "${inventory}" lua_ident_declared)
  string(JSON defined GET "${inventory}" lua_ident_defined)
  if(NOT count EQUAL 156 OR NOT declared OR NOT defined)
    message(FATAL_ERROR "Lua public function or identity contract changed")
  endif()
elseif(CPKT_KIND STREQUAL "mqttc")
  string(JSON count LENGTH "${inventory}" unheadered_dynamic_symbols)
  string(JSON name GET "${inventory}" unheadered_dynamic_symbols 0)
  if(NOT count EQUAL 1 OR NOT name STREQUAL "mqtt_fixed_header_rules")
    message(FATAL_ERROR "Unexpected unheadered MQTT-C dynamic symbols")
  endif()
endif()
