cmake_minimum_required(VERSION 3.21)
include("${CPKT_ROOT}/tests/test-command.cmake")
set(work "${CPKT_SCRATCH}/archive-reuse")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}/payload")
file(WRITE "${work}/payload/sample" "original archive input\n")
set(archive "${work}/fixture.tar.gz")
cpkt_test_command(bash "${CPKT_ROOT}/scripts/archive.sh" "${work}/payload" "${archive}")
file(TIMESTAMP "${archive}" before "%s")
file(SHA256 "${archive}" original)
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1.1)
cpkt_test_command(bash "${CPKT_ROOT}/scripts/archive.sh" "${work}/payload" "${archive}")
file(TIMESTAMP "${archive}" after "%s")
if(NOT before STREQUAL after)
  message(FATAL_ERROR "Identical archive bytes invalidated downstream checks")
endif()
file(WRITE "${work}/payload/sample" "changed archive input\n")
cpkt_test_command(bash "${CPKT_ROOT}/scripts/archive.sh" "${work}/payload" "${archive}")
file(SHA256 "${archive}" changed)
if(original STREQUAL changed)
  message(FATAL_ERROR "Changed archive input reused stale bytes")
endif()
