cmake_minimum_required(VERSION 3.21)
include("${CPKT_REPO}/tests/test-command.cmake")
file(READ "${CPKT_REPO}/tests/contracts/auth_native_api.json" snapshot)
string(JSON macros GET "${snapshot}" "${CPKT_TARGET}" "${CPKT_PROVIDER}" macros)
cpkt_test_command("${CPKT_CC}" -std=gnu99 -dM -E
  "-I${CPKT_REPO}/include" "-I${CPKT_INCLUDE}" "${CPKT_PROBE}")
set(observed "\n${CPKT_TEST_OUTPUT}")
string(JSON count LENGTH "${macros}")
math(EXPR last "${count}-1")
foreach(index RANGE 0 ${last})
  string(JSON name MEMBER "${macros}" ${index})
  string(JSON definition GET "${macros}" "${name}")
  string(FIND "${observed}" "\n#define ${name} ${definition}\n" found)
  if(found LESS 0)
    message(FATAL_ERROR "Native ${CPKT_PROVIDER} macro changed: ${name}")
  endif()
endforeach()
