cmake_minimum_required(VERSION 3.21)
include("${CPKT_REPO}/tests/test-command.cmake")
set(work "${CPKT_BINARY}/auth-mutations")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}/include")
file(COPY "${CPKT_REPO}/include/cpkt" DESTINATION "${work}/include")
set(command "${CPKT_CC}" -std=gnu99 -Werror "-I${work}/include"
  -c "${CPKT_BINARY}/generated/contracts/auth_facade.c" -o "${work}/probe.o")
function(mutate file before after)
  file(READ "${work}/include/cpkt/${file}" original)
  string(FIND "${original}" "${before}" found)
  if(found LESS 0)
    message(FATAL_ERROR "Missing mutation site: ${before}")
  endif()
  string(REPLACE "${before}" "${after}" changed "${original}")
  file(WRITE "${work}/include/cpkt/${file}" "${changed}")
  cpkt_test_failure(error ${command})
  file(WRITE "${work}/include/cpkt/${file}" "${original}")
endfunction()
mutate(sasl_plugin.h "void cpkt_sasl_md5_initialize(cpkt_sasl_md5_context *context);"
  "void cpkt_sasl_md5_initialize_REMOVED(cpkt_sasl_md5_context *context);")
mutate(sasl_plugin.h "const unsigned char *bytes, unsigned long length);"
  "const void *bytes, unsigned long length);")
mutate(sasl.h "unsigned long value_count;" "unsigned long missing_value_count;")
mutate(sasl.h "cpkt_sasl_simple_callback simple;" "int simple;")
mutate(sasl.h "typedef int (*cpkt_sasl_simple_callback)(void *context, int id,"
  "typedef int (*cpkt_sasl_simple_callback)(void *context, long id,")
mutate(sasl.h "unsigned long value_count;\n  unsigned long total_value_bytes;"
  "unsigned long total_value_bytes;\n  unsigned long value_count;")
mutate(gssapi.h "  CPKT_GSS_OID_HOSTBASED_SERVICE_X,\n  CPKT_GSS_OID_COMPOSITE_EXPORT_NAME,"
  "  CPKT_GSS_OID_COMPOSITE_EXPORT_NAME,\n  CPKT_GSS_OID_HOSTBASED_SERVICE_X,")
file(MAKE_DIRECTORY "${work}/native")
file(COPY "${CPKT_EXTERNAL_ROOT}/cyrus-sasl/install/include/sasl" DESTINATION "${work}/native")
set(command "${CPKT_CC}" -std=gnu99 -Werror -Wno-deprecated-declarations
  "-I${CPKT_REPO}/include" "-I${work}/native"
  -c "${CPKT_BINARY}/generated/contracts/auth_sasl.c" -o "${work}/probe.o")
function(mutate_native file before after)
  file(READ "${work}/native/sasl/${file}" original)
  string(FIND "${original}" "${before}" found)
  if(found LESS 0)
    message(FATAL_ERROR "Missing native mutation site: ${before}")
  endif()
  string(REPLACE "${before}" "${after}" changed "${original}")
  file(WRITE "${work}/native/sasl/${file}" "${changed}")
  cpkt_test_failure(error ${command})
  file(WRITE "${work}/native/sasl/${file}" "${original}")
endfunction()
mutate_native(sasl.h "#define SASL_OK          0" "#define SASL_OK          7")
mutate_native(saslplug.h "SASL_INFO_LIST_START = 0" "SASL_INFO_LIST_START = 7")
mutate_native(saslplug.h "SASL_CB_DISP_NONE = 0" "SASL_CB_DISP_NONE = 7")
mutate_native(sasl.h "SASL_VRFY_OTHER=3" "SASL_VRFY_OTHER=7")
mutate_native(md5.h "UINT4 count[2];" "UINT4 count[3];")
mutate_native(sasl.h "sasl_client_init(const sasl_callback_t *callbacks)" "sasl_client_init(const void *callbacks)")
mutate_native(sasl.h "    sasl_ssf_t min_ssf;\n    sasl_ssf_t max_ssf;"
  "    sasl_ssf_t max_ssf;\n    sasl_ssf_t min_ssf;")
