include("${CPKT_REPO}/tests/test-command.cmake")
set(work "${CPKT_SCRATCH}/auth-discovery")
file(REMOVE_RECURSE "${work}")
set(prefix "${work}/relocated sdk")
file(MAKE_DIRECTORY "${prefix}/include" "${prefix}/lib/cmake/OpenSSL" "${work}/host/lib/cmake/OpenSSL")
file(WRITE "${prefix}/lib/cmake/OpenSSL/OpenSSLConfig.cmake" [=[get_filename_component(_prefix "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
foreach(component SSL Crypto)
  add_library(OpenSSL::${component} STATIC IMPORTED)
  set_target_properties(OpenSSL::${component} PROPERTIES IMPORTED_LOCATION "${_prefix}/lib/fixture-${component}.a")
endforeach()
set(OpenSSL_FOUND TRUE)
]=])
file(WRITE "${work}/host/lib/cmake/OpenSSL/OpenSSLConfig.cmake" "message(FATAL_ERROR \"Host OpenSSL selected\")\n")
file(READ "${CPKT_REPO}/cmake/package_metadata.cmake" metadata)
foreach(package CpktGssapi Kerberos5)
  set(marker "cpkt_metadata_file(WRITE \"\${_stage_root}/lib/cmake/${package}/")
  string(FIND "${metadata}" "${marker}" start)
  if(start LESS 0)
    message(FATAL_ERROR "Missing actual ${package} metadata generator")
  endif()
  string(SUBSTRING "${metadata}" ${start} -1 tail)
  string(FIND "${tail}" "\n)\n" end)
  math(EXPR length "${end}+3")
  string(SUBSTRING "${tail}" 0 ${length} recipe)
  string(REPLACE "cpkt_metadata_file(" "file(" recipe "${recipe}")
  file(MAKE_DIRECTORY "${prefix}/lib/cmake/${package}")
  file(WRITE "${work}/${package}-generate.cmake" "set(_stage_root [==[${prefix}]==])\nset(_cpkt_static_library_suffix .a)\nset(_cpkt_shared_library_suffix .so)\n${recipe}")
  cpkt_test_command("${CMAKE_COMMAND}" -P "${work}/${package}-generate.cmake")
  foreach(mode isolated host-decoy)
    set(source "${work}/${package}-${mode}")
    file(MAKE_DIRECTORY "${source}")
    set(content [=[cmake_minimum_required(VERSION 3.21)
project(auth_discovery C)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
set(CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH FALSE)
set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH FALSE)
find_package(@package@ CONFIG REQUIRED)
if(NOT OpenSSL_DIR STREQUAL "${CPKT_EXPECTED_PREFIX}/lib/cmake/OpenSSL")
  message(FATAL_ERROR "Authentication package did not select adjacent OpenSSL")
endif()
get_target_property(location OpenSSL::SSL IMPORTED_LOCATION)
string(FIND "${location}" "${CPKT_EXPECTED_PREFIX}/lib/" in_sdk)
if(NOT in_sdk EQUAL 0)
  message(FATAL_ERROR "OpenSSL target points outside SDK")
endif()
]=])
    string(CONFIGURE "${content}" content @ONLY)
    file(WRITE "${source}/CMakeLists.txt" "${content}")
    set(arguments "-DCMAKE_C_COMPILER=${CPKT_CC}" -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY
      "-D${package}_DIR=${prefix}/lib/cmake/${package}" "-DCPKT_EXPECTED_PREFIX=${prefix}")
    if(CPKT_TOOLCHAIN)
      list(APPEND arguments "-DCMAKE_TOOLCHAIN_FILE=${CPKT_TOOLCHAIN}")
    endif()
    if(mode STREQUAL "host-decoy")
      list(APPEND arguments "-DCMAKE_PREFIX_PATH=${work}/host")
    endif()
    cpkt_test_command("${CMAKE_COMMAND}" -S "${source}" -B "${source}/build" ${arguments})
  endforeach()
endforeach()
