cmake_minimum_required(VERSION 3.21)
file(READ "${CPKT_SOURCE}" source)
string(FIND "${source}" "int sasl_getprop(" get_start)
string(FIND "${source}" "int sasl_setprop(" set_start)
string(FIND "${source}" "static int sasl_usererr(" set_end)
if(get_start LESS 0 OR set_start LESS get_start OR set_end LESS set_start)
  message(FATAL_ERROR "Missing SASL property implementations")
endif()
math(EXPR length "${set_start}-${get_start}")
string(SUBSTRING "${source}" ${get_start} ${length} get_body)
math(EXPR length "${set_end}-${set_start}")
string(SUBSTRING "${source}" ${set_start} ${length} set_body)
set(expected_get USERNAME DEFUSERREALM IPLOCALPORT IPREMOTEPORT PLUGERR SERVICE
  SERVERFQDN AUTHSOURCE MECHNAME AUTHUSER APPNAME AUTH_EXTERNAL SSF MAXOUTBUF SSF_EXTERNAL
  GETOPTCTX CALLBACK DELEGATEDCREDS GSS_CREDS GSS_LOCAL_NAME GSS_PEER_NAME HTTP_REQUEST SEC_PROPS)
set(expected_set DEFUSERREALM IPLOCALPORT IPREMOTEPORT APPNAME AUTH_EXTERNAL SSF_EXTERNAL
  SEC_PROPS GSS_CREDS CHANNEL_BINDING HTTP_REQUEST)
foreach(kind get set)
  string(REGEX MATCHALL "case[ \t]+SASL_[A-Za-z0-9_]+[ \t]*:" cases "${${kind}_body}")
  string(REGEX REPLACE "case[ \t]+SASL_|[ \t]*:" "" cases "${cases}")
  list(REMOVE_DUPLICATES cases)
  list(SORT cases)
  list(SORT expected_${kind})
  if(NOT cases STREQUAL expected_${kind})
    message(FATAL_ERROR "SASL ${kind} property coverage changed: ${cases}")
  endif()
endforeach()
