cmake_minimum_required(VERSION 3.21)
include("${CPKT_ROOT}/tests/test-command.cmake")
set(work "${CPKT_SCRATCH}/checksum-scope")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}")
set(binary cpkt-1.2.3-x86_64-linux-gnu.tar.gz)
set(source cpkt-1.2.3.tar.gz)
file(WRITE "${work}/${binary}" "binary bytes")
file(WRITE "${work}/${source}" "source bytes")
file(SHA256 "${work}/${binary}" binary_hash)
file(SHA256 "${work}/${source}" source_hash)
set(manifest "${work}/CHECKSUMS")
set(command "${CMAKE_COMMAND}" "-DCPKT_BASE=${work}" "-DCPKT_MANIFEST=${manifest}"
  -DCPKT_VERSION=1.2.3)
set(check -P "${CPKT_ROOT}/cmake/verify-checksums.cmake")
file(WRITE "${manifest}" "${binary_hash}  ${binary}\n")
cpkt_test_command(${command} -DCPKT_SCOPE=binary "-DCPKT_FILES=${binary}" ${check})
cpkt_test_failure("Stale/unlisted" ${command} -DCPKT_SCOPE=selected "-DCPKT_FILES=${binary}" ${check})
cpkt_test_failure("Incomplete" ${command} -DCPKT_SCOPE=release "-DCPKT_FILES=${binary}\\;${source}" ${check})
file(WRITE "${work}/cpkt-1.2.2.tar.gz" "stale source")
cpkt_test_failure("Stale/unlisted" ${command} -DCPKT_SCOPE=binary "-DCPKT_FILES=${binary}" ${check})
file(REMOVE "${work}/cpkt-1.2.2.tar.gz")
file(WRITE "${work}/cpkt-1.2.3-extra.zip" "unexpected artifact")
cpkt_test_failure("Stale/unlisted" ${command} -DCPKT_SCOPE=binary "-DCPKT_FILES=${binary}" ${check})
file(REMOVE "${work}/cpkt-1.2.3-extra.zip")
file(WRITE "${manifest}" "${binary_hash}  ${binary}\n${source_hash}  ${source}\n")
cpkt_test_command(${command} -DCPKT_SCOPE=release "-DCPKT_FILES=${binary}\\;${source}" ${check})
file(APPEND "${work}/${source}" "changed")
cpkt_test_failure("Checksum mismatch" ${command} -DCPKT_SCOPE=release "-DCPKT_FILES=${binary}\\;${source}" ${check})
