cmake_minimum_required(VERSION 3.21)
include("${CPKT_REPO}/tests/test-command.cmake")
if(EXISTS "${CPKT_BINARY}/build.ninja")
  cpkt_test_command("${CPKT_MAKE_PROGRAM}" -C "${CPKT_BINARY}" -t commands "${CPKT_EXECUTABLE}")
  string(REPLACE "\n" ";" commands "${CPKT_TEST_OUTPUT}")
  set(link "")
  foreach(command IN LISTS commands)
    if(command MATCHES " -o ${CPKT_EXECUTABLE}( |$)")
      set(link "${command}")
    endif()
  endforeach()
else()
  file(READ "${CPKT_BINARY}/CMakeFiles/${CPKT_EXECUTABLE}.dir/link.txt" link)
endif()
foreach(path IN LISTS CPKT_PATHS)
  string(FIND "${link}" "-Wl,-rpath,${path}" found)
  if(found LESS 0)
    message(FATAL_ERROR "Missing Darwin test runtime path: ${path}")
  endif()
endforeach()
