include("${CPKT_REPO}/cmake/CpktDependencyArchiveCache.cmake")
file(SHA256 "${CPKT_WORK}/fixture.tar.gz" digest)
file(READ "${CPKT_WORK}/port" port)
set(CPKT_DEPENDENCY_CACHE "${CPKT_WORK}/shared cache")
set(CPKT_DEPENDENCY_DOWNLOAD_RETRIES 1)
set(CPKT_DEPENDENCY_DOWNLOAD_TIMEOUT 5)
set(CPKT_DEPENDENCY_DOWNLOAD_INACTIVITY_TIMEOUT 5)
set(CPKT_DEPENDENCY_CACHE_LOCK_TIMEOUT 5)
set(origin "http://127.0.0.1:${port}")
function(acquire name endpoint count)
  cpkt_acquire_dependency_archive(archive NAME "${name}" SHA256 "${digest}" URLS "${origin}/${endpoint}")
  file(SHA256 "${archive}" actual)
  if(NOT actual STREQUAL digest)
    message(FATAL_ERROR "Cache returned corrupt bytes")
  endif()
  file(STRINGS "${CPKT_WORK}/requests" requests)
  list(LENGTH requests actual_count)
  if(NOT actual_count EQUAL count)
    message(FATAL_ERROR "Unexpected acquisition requests: ${requests}")
  endif()
  foreach(request IN LISTS requests)
    if(NOT request STREQUAL "GET /fixture.tar.gz")
      message(FATAL_ERROR "Verified cache hit attempted network access: ${request}")
    endif()
  endforeach()
endfunction()
acquire(original.tar.gz fixture.tar.gz 1)
acquire(renamed.tar.gz must-not-fetch 1)
set(entry "${CPKT_DEPENDENCY_CACHE}/archives/sha256/${digest}")
file(WRITE "${entry}/renamed.tar.gz" corrupt)
acquire(renamed.tar.gz must-not-fetch 1)
file(GLOB archives "${entry}/*")
foreach(archive IN LISTS archives)
  file(WRITE "${archive}" corrupt)
endforeach()
acquire(original.tar.gz fixture.tar.gz 2)
file(GLOB archives "${entry}/*")
file(REMOVE ${archives})
file(COPY_FILE "${CPKT_WORK}/fixture.tar.gz" "${entry}/.archive.part-test")
acquire(original.tar.gz fixture.tar.gz 3)
