cmake_minimum_required(VERSION 3.21)
if(NOT CPKT_SCRATCH)
  set(CPKT_SCRATCH "${CMAKE_CURRENT_BINARY_DIR}")
endif()
set(work "${CPKT_SCRATCH}/dependency-input-fixture")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}/source")
file(WRITE "${work}/source/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.21)
project(dependency_inputs NONE)
include("${CPKT_ROOT}/cmake/CpktDependencyContract.cmake")
include("${CPKT_ROOT}/cmake/CpktComponentInventory.cmake")
set(CPKT_GROUP core)
set(CPKT_INVENTORY [==[{"components":{"base":{"group":"core","dependencies":[]},"sample":{"group":"core","dependencies":["base"]},"unrelated":{"group":"core","dependencies":[]}}}]==])
cpkt_select_components(CPKT_ACTIVE_COMPONENTS)
if(CPKT_DEPENDENCY STREQUAL "base")
  set(expected_components base)
else()
  set(expected_components "base;sample")
endif()
if(CPKT_DEPENDENCY_PRODUCER AND NOT CPKT_ACTIVE_COMPONENTS STREQUAL expected_components)
  message(FATAL_ERROR "Selected preparation includes unrelated components")
endif()
set(CPKT_TARGET_ID fixture)
set(CPKT_DEPENDENCY_CONTRACT_ROOT "${CMAKE_SOURCE_DIR}/.cache/inputs")
set(CPKT_EXTERNAL_ROOT_LIFECYCLE_OWNED ON)
set(CPKT_DEPENDENCY_BUILD_ROOT_LIFECYCLE_OWNED ON)
cpkt_prepare_dependency_component(NAME base
  BUILD_ROOT "${CMAKE_SOURCE_DIR}/.cache/deps-build/fixture/base"
  INSTALL_ROOT "${CMAKE_SOURCE_DIR}/.cache/deps/fixture/base/install"
  VARIABLES BASE_VERSION)
cpkt_prepare_dependency_component(NAME sample
  BUILD_ROOT "${CMAKE_SOURCE_DIR}/.cache/deps-build/fixture/sample"
  INSTALL_ROOT "${CMAKE_SOURCE_DIR}/.cache/deps/fixture/sample/install"
  VARIABLES SAMPLE_VERSION DEPENDS base)
]=])
function(configure producer version expected)
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${work}/source" -B "${work}/graph"
    "-DCPKT_ROOT=${CPKT_ROOT}" "-DCPKT_DEPENDENCY_PRODUCER=${producer}"
    -DCPKT_DEPENDENCY=sample
    "-DSAMPLE_VERSION=${version}" ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(expected STREQUAL "pass" AND NOT status EQUAL 0)
    message(FATAL_ERROR "Configure failed: ${out}${err}")
  elseif(expected STREQUAL "fail" AND status EQUAL 0)
    message(FATAL_ERROR "Missing/stale prerequisite was accepted")
  endif()
endfunction()
configure(OFF 1 fail)
configure(ON 1 pass)
set(base_complete "${work}/source/.cache/inputs/fixture/base.complete")
file(WRITE "${base_complete}" "")
set(inputs "${work}/source/.cache/inputs/fixture/sample.inputs")
set(complete "${work}/source/.cache/inputs/fixture/sample.complete")
set(install "${work}/source/.cache/deps/fixture/sample/install")
set(build "${work}/source/.cache/deps-build/fixture/sample")
file(WRITE "${install}/artifact" "fixture installation")
file(WRITE "${build}/artifact" "fixture build")
file(WRITE "${complete}" "")
file(WRITE "${work}/source/.cache/deps/fixture/other/artifact" "unrelated")
file(TIMESTAMP "${inputs}" before "%s")
configure(ON 1 pass)
file(TIMESTAMP "${inputs}" after "%s")
if(NOT before STREQUAL after OR NOT EXISTS "${install}/artifact")
  message(FATAL_ERROR "No-op configure modified inputs or installed output")
endif()
configure(OFF 1 pass)
configure(OFF 2 fail)
if(NOT EXISTS "${install}/artifact")
  message(FATAL_ERROR "Borrowed configuration modified its prerequisite")
endif()
configure(ON 2 pass)
if(EXISTS "${install}" OR EXISTS "${build}" OR EXISTS "${complete}" OR
    NOT EXISTS "${work}/source/.cache/deps/fixture/other/artifact")
  message(FATAL_ERROR "Input invalidation removed the wrong scope")
endif()
# Preparing just the prerequisite must invalidate dependents on the next call.
file(WRITE "${install}/artifact" "fixture installation")
file(WRITE "${build}/artifact" "fixture build")
file(WRITE "${complete}" "")
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.05)
configure(ON 2 pass -DCPKT_DEPENDENCY=base -DBASE_VERSION=2)
file(WRITE "${base_complete}" "")
configure(OFF 2 fail)
if(NOT EXISTS "${install}/artifact" OR NOT EXISTS "${complete}")
  message(FATAL_ERROR "Stale dependent consumer modified borrowed output")
endif()
configure(ON 2 pass)
if(EXISTS "${install}" OR EXISTS "${build}" OR EXISTS "${complete}" OR
    NOT EXISTS "${base_complete}" OR
    NOT EXISTS "${work}/source/.cache/deps/fixture/other/artifact")
  message(FATAL_ERROR "Selected prerequisite change invalidated the wrong scope")
endif()
file(WRITE "${work}/borrowed/artifact" "borrowed")
file(MAKE_DIRECTORY "${work}/source/.cache/deps/fixture/sample")
file(CREATE_LINK "${work}/borrowed" "${install}" SYMBOLIC RESULT link_status)
if(NOT link_status STREQUAL "0")
  message(FATAL_ERROR "Cannot create fixture symlink: ${link_status}")
endif()
configure(ON 3 fail)
if(NOT EXISTS "${work}/borrowed/artifact")
  message(FATAL_ERROR "Cleanup touched a borrowed root")
endif()
file(REMOVE_RECURSE "${work}")
message(STATUS "Native input reuse, borrowed prerequisites and cleanup boundaries passed")
