include("${CPKT_REPO}/tests/test-command.cmake")
set(work "${CPKT_SCRATCH}/install-order-${CPKT_GENERATOR}")
file(REMOVE_RECURSE "${work}")
foreach(ordered OFF ON)
  set(binary "${work}/${ordered}")
  cpkt_test_command("${CMAKE_COMMAND}" -S "${CPKT_REPO}/tests/install-order" -B "${binary}"
    -G "${CPKT_GENERATOR}" "-DCPKT_REPO=${CPKT_REPO}" "-DENFORCE_ORDER=${ordered}")
  if(NOT ordered)
    cpkt_test_failure("Concurrent common-prefix installs" "${CMAKE_COMMAND}" --build "${binary}" --parallel 2)
    continue()
  endif()
  cpkt_test_command("${CMAKE_COMMAND}" --build "${binary}" --parallel 2)
  file(STRINGS "${binary}/events" events)
  set(expected "static install begin;static install end;shared build begin;shared build end;shared install begin;shared install end")
  set(sorted "${events}")
  list(SORT sorted)
  list(SORT expected)
  list(FIND events "static install begin" begin)
  list(FIND events "shared build end" overlap)
  list(FIND events "static install end" end)
  list(FIND events "shared install begin" shared_begin)
  list(FIND events "shared install end" shared_end)
  file(READ "${binary}/config" final)
  if(NOT sorted STREQUAL expected OR NOT final STREQUAL "shared"
      OR NOT (begin LESS overlap AND overlap LESS end AND end LESS shared_begin AND shared_begin LESS shared_end))
    message(FATAL_ERROR "Incorrect install order: ${events}; final=${final}")
  endif()
endforeach()
