cmake_minimum_required(VERSION 3.21)
include("${CPKT_REPO}/tests/test-command.cmake")
set(work "${CPKT_BINARY}/export-catalog-${CPKT_GENERATOR}")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}/source/cmake/exports")
file(WRITE "${work}/source/probe.c" "int cpkt_export_probe_alpha(void) { return 1; }\nint cpkt_export_probe_beta(void) { return 2; }\n")
file(WRITE "${work}/source/cmake/exports/export_probe.txt" "cpkt_export_probe_alpha\n")
file(WRITE "${work}/source/CMakeLists.txt" [=[cmake_minimum_required(VERSION 3.21)
project(export_probe C)
include("${CPKT_REPO}/cmake/CpktExports.cmake")
add_library(export_probe SHARED probe.c)
target_compile_options(export_probe PRIVATE -std=c89 -Wall -Wextra -Werror)
cpkt_apply_auth_export_catalog(export_probe export_probe)
]=])
cpkt_test_command("${CMAKE_COMMAND}" -S "${work}/source" -B "${work}/graph" -G "${CPKT_GENERATOR}"
  "-DCPKT_REPO=${CPKT_REPO}" "-DCMAKE_TOOLCHAIN_FILE=${CPKT_TOOLCHAIN}")
set(library "${work}/graph/libexport_probe.so")
foreach(state alpha both beta)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.05)
  if(state STREQUAL "both")
    set(names "cpkt_export_probe_alpha;cpkt_export_probe_beta")
  else()
    set(names "cpkt_export_probe_${state}")
  endif()
  string(REPLACE ";" "\n" catalog "${names}")
  file(WRITE "${work}/source/cmake/exports/export_probe.txt" "${catalog}\n")
  cpkt_test_command("${CMAKE_COMMAND}" --build "${work}/graph" --target export_probe)
  cpkt_test_command("${CPKT_NM}" -D --defined-only "${library}")
  string(REGEX MATCHALL "cpkt_export_probe_[a-z]+" actual "${CPKT_TEST_OUTPUT}")
  list(SORT actual)
  list(SORT names)
  if(NOT actual STREQUAL names)
    message(FATAL_ERROR "Catalog-only change did not update public exports: ${actual}")
  endif()
  execute_process(COMMAND stat -c %y "${library}" OUTPUT_VARIABLE before)
  cpkt_test_command("${CMAKE_COMMAND}" --build "${work}/graph" --target export_probe)
  execute_process(COMMAND stat -c %y "${library}" OUTPUT_VARIABLE after)
  if(NOT before STREQUAL after)
    message(FATAL_ERROR "Unchanged export catalog caused a relink")
  endif()
endforeach()
