cmake_minimum_required(VERSION 3.21)
include("${CPKT_REPO}/tests/test-command.cmake")
set(work "${CPKT_BINARY}/lua-registration")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}/source/cmake")
file(COPY_FILE "${CPKT_REPO}/cmake/components.json" "${work}/source/cmake/components.json")
file(WRITE "${work}/source/CMakeLists.txt" [=[cmake_minimum_required(VERSION 3.21)
project(lua_registration NONE)
enable_testing()
set(CPKT_GROUP core)
set(CPKT_CAN_RUN_TARGET_EXECUTABLES OFF)
set(CMAKE_SYSTEM_NAME Darwin)
set(CPKT_TARGET_ID arm64-apple-darwin)
set(CPKT_HOST_PYTHON_EXECUTABLE python3)
set(CPKT_PYTHON3_EXECUTABLE python3)
set(CMAKE_NM nm)
set(CMAKE_C_COMPILER cc)
set(CPKT_EXTERNAL_ROOT "${CMAKE_BINARY_DIR}/deps")
set(_cpkt_lua_inventory_symbol_format macho)
set(CPKT_LUA_FACADE_HEADER "${CMAKE_SOURCE_DIR}/lua.h")
include("${CPKT_REPO}/cmake/CpktGroups.cmake")
include("${CPKT_REPO}/cmake/CpktMutationPaths.cmake")
include("${CPKT_REPO}/cmake/CpktAPIInventories.cmake")
foreach(name cpkt::lua_static cpkt::lua_shared cpkt_lua_shared)
  add_library(${name} UNKNOWN IMPORTED)
  set_target_properties(${name} PROPERTIES IMPORTED_LOCATION "${CMAKE_SOURCE_DIR}/lua.a"
    INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_SOURCE_DIR}")
endforeach()
include("${CPKT_REPO}/cmake/CpktLuaInventoryTest.cmake")
include("${CPKT_REPO}/cmake/CpktLuaExportsTest.cmake")
get_property(tests DIRECTORY PROPERTY TESTS)
foreach(required lua_api_inventory lua_export_policy)
  if(NOT required IN_LIST tests)
    message(FATAL_ERROR "Darwin did not register ${required} without a runner")
  endif()
endforeach()
]=])
cpkt_test_command("${CMAKE_COMMAND}" -S "${work}/source" -B "${work}/graph" "-DCPKT_REPO=${CPKT_REPO}")
