include("${CPKT_REPO}/tests/test-command.cmake")
set(work "${CPKT_SCRATCH}/openssl-builddata")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}/util" "${work}/exporters")
set(inputs build.info exporters/build.info util/mkinstallvars.pl util/mkbuildinf.pl)
foreach(input IN LISTS inputs)
  file(COPY_FILE "${CPKT_SOURCE}/${input}" "${work}/${input}")
endforeach()
cpkt_test_command("${CMAKE_COMMAND}" "-DOPENSSL_SOURCE_DIR=${work}" -P "${CPKT_REPO}/cmake/patch_openssl_buildinfo.cmake")
foreach(input IN LISTS inputs)
  file(SHA256 "${work}/${input}" before_${input})
endforeach()
cpkt_test_command("${CMAKE_COMMAND}" "-DOPENSSL_SOURCE_DIR=${work}" -P "${CPKT_REPO}/cmake/patch_openssl_buildinfo.cmake")
foreach(input IN LISTS inputs)
  file(SHA256 "${work}/${input}" after)
  if(NOT after STREQUAL before_${input})
    message(FATAL_ERROR "OpenSSL patch is not idempotent: ${input}")
  endif()
endforeach()
function(generate input marker directory output)
  file(STRINGS "${work}/${input}" lines)
  set(recipe "")
  foreach(line IN LISTS lines)
    string(FIND "${line}" "${marker}" start)
    if(start EQUAL 0)
      string(REPLACE "${marker}" "" line "${line}")
      set(collect ON)
    endif()
    if(collect)
      string(REGEX REPLACE "\\\\$" "" part "${line}")
      string(APPEND recipe " ${part}")
      if(NOT line MATCHES "\\\\$")
        break()
      endif()
    endif()
  endforeach()
  foreach(key VERSION LIB_EX_LIBS SRCDIR INSTALLTOP LIBDIR libdir ENGINESDIR MODULESDIR PKGCONFIGDIR CMAKECONFIGDIR)
    string(REPLACE "$(${key})" "${${key}}" recipe "${recipe}")
  endforeach()
  separate_arguments(arguments UNIX_COMMAND "${recipe}")
  execute_process(COMMAND perl ${arguments} WORKING_DIRECTORY "${directory}"
    RESULT_VARIABLE result OUTPUT_VARIABLE content ERROR_VARIABLE error)
  if(NOT result EQUAL 0 OR error)
    message(FATAL_ERROR "OpenSSL metadata generator failed: ${error}")
  endif()
  file(WRITE "${work}/${output}" "${content}")
endfunction()
set(VERSION test-version)
set(LIB_EX_LIBS "-ldl -pthread")
set(SRCDIR .)
generate(build.info "GENERATE[builddata.pm]=" "${work}" builddata.pm)
execute_process(COMMAND perl -I. -Mbuilddata -e
  "for my $path (@OpenSSL::safe::installdata::LIBDIR, @OpenSSL::safe::installdata::libdir, @OpenSSL::safe::installdata::PKGCONFIGDIR, @OpenSSL::safe::installdata::CMAKECONFIGDIR) { die qq(unexpected build directory: $path) if $path ne $ARGV[0]; }" "${work}"
  WORKING_DIRECTORY "${work}" RESULT_VARIABLE result ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Incorrect OpenSSL build directories: ${error}")
endif()
set(INSTALLTOP /opt/cpkt)
set(LIBDIR lib)
set(libdir /opt/cpkt/lib)
set(ENGINESDIR /opt/cpkt/lib/engines-3)
set(MODULESDIR /opt/cpkt/lib/ossl-modules)
set(PKGCONFIGDIR /opt/cpkt/lib/pkgconfig)
set(CMAKECONFIGDIR /opt/cpkt/lib/cmake/OpenSSL)
generate(exporters/build.info "GENERATE[../installdata.pm]=" "${work}/exporters" installdata.pm)
execute_process(COMMAND perl -I. -Minstalldata -e
  "die 'wrong install libdir' if $OpenSSL::safe::installdata::LIBDIR[0] ne '/opt/cpkt/lib'; die 'wrong install pkg-config directory' if $OpenSSL::safe::installdata::PKGCONFIGDIR[0] ne '/opt/cpkt/lib/pkgconfig'; die 'wrong install CMake directory' if $OpenSSL::safe::installdata::CMAKECONFIGDIR[0] ne '/opt/cpkt/lib/cmake/OpenSSL';"
  WORKING_DIRECTORY "${work}" RESULT_VARIABLE result ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Incorrect OpenSSL install directories: ${error}")
endif()
execute_process(COMMAND perl util/mkinstallvars.pl PREFIX=. WORKING_DIRECTORY "${work}"
  RESULT_VARIABLE result ERROR_VARIABLE error)
if(NOT error MATCHES "No value given for")
  message(FATAL_ERROR "OpenSSL missing-input warnings were hidden")
endif()
