include("${CPKT_REPO}/tests/test-command.cmake")
set(work "${CPKT_BINARY}/recipe-graph")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}/source")
file(COPY "${CPKT_REPO}/cmake" "${CPKT_REPO}/src" DESTINATION "${work}/source")
file(READ "${CPKT_REPO}/CMakeLists.txt" top)
string(FIND "${top}" "set(CPKT_BUNDLE_VERSION" start)
string(FIND "${top}" "set(CPKT_DOWNLOAD_ROOT" end)
math(EXPR length "${end}-${start}")
string(SUBSTRING "${top}" ${start} ${length} pins)
set(project [=[cmake_minimum_required(VERSION 3.21)
project(recipe_graph C CXX)
find_package(Threads REQUIRED)
set(CPKT_BUILD_DEPENDENCIES ON)
set(CPKT_TARGET_ID x86_64-linux-gnu)
set(CPKT_TARGET_ARCH x86_64)
set(CPKT_TARGET_OS linux)
set(CPKT_TARGET_LIBC gnu)
set(CPKT_DEPENDENCY_BUILD_TYPE Release)
set(CPKT_DEPENDENCY_BUILD_JOBS 2)
set(CPKT_EXTERNAL_ROOT "${CMAKE_BINARY_DIR}/deps")
set(CPKT_DEPENDENCY_BUILD_ROOT "${CMAKE_BINARY_DIR}/deps-build")
set(CPKT_DOWNLOAD_ROOT "${CMAKE_BINARY_DIR}/downloads")
include(cmake/CpktDependencies.cmake)
# Only acquisition is replaced. No generated recipe is executed here.
macro(cpkt_cached_external_project_add)
  ExternalProject_Add(${ARGV})
endmacro()
]=])
string(APPEND project "\n${pins}\n")
file(READ "${CPKT_REPO}/cmake/components.json" inventory)
string(JSON count LENGTH "${inventory}" components)
math(EXPR last "${count}-1")
foreach(index RANGE 0 ${last})
  string(JSON name MEMBER "${inventory}" components ${index})
  string(JSON functions LENGTH "${inventory}" components "${name}" recipe_functions)
  math(EXPR function_last "${functions}-1")
  string(JSON recipe GET "${inventory}" components "${name}" recipe_functions ${function_last})
  string(APPEND project "get_property(before GLOBAL PROPERTY CPKT_DEPENDENCY_TARGETS)\n${recipe}()\nget_property(after GLOBAL PROPERTY CPKT_DEPENDENCY_TARGETS)\nset(owned \"\${after}\")\nif(before)\n  list(REMOVE_ITEM owned \${before})\nendif()\nif(NOT owned)\n  message(FATAL_ERROR \"Missing ${name} producer targets\")\nendif()\nadd_custom_target(cpkt_deps_${name} DEPENDS \${owned})\n")
endforeach()
file(WRITE "${work}/source/CMakeLists.txt" "${project}")
foreach(generator Ninja "Unix Makefiles")
  cpkt_test_command("${CMAKE_COMMAND}" -S "${work}/source" -B "${work}/${generator}" -G "${generator}"
    "-DCMAKE_TOOLCHAIN_FILE=${CPKT_TOOLCHAIN}" "-DCPKT_TOOLCHAIN_ROOT=${CPKT_TOOLCHAIN_ROOT}")
endforeach()
