cmake_minimum_required(VERSION 3.21)
include("${CPKT_REPO}/tests/test-command.cmake")
if(CPKT_TARGET STREQUAL "x86_64-linux-gnu")
  set(name ld-linux-x86-64.so.2)
elseif(CPKT_TARGET STREQUAL "x86_64-linux-musl")
  set(name ld-musl-x86_64.so.1)
elseif(CPKT_TARGET STREQUAL "aarch64-linux-gnu")
  set(name ld-linux-aarch64.so.1)
elseif(CPKT_TARGET STREQUAL "aarch64-linux-musl")
  set(name ld-musl-aarch64.so.1)
elseif(CPKT_TARGET STREQUAL "armhf-linux-gnu")
  set(name ld-linux-armhf.so.3)
elseif(CPKT_TARGET STREQUAL "armhf-linux-musl")
  set(name ld-musl-armhf.so.1)
else()
  message(FATAL_ERROR "Unsupported loader target: ${CPKT_TARGET}")
endif()
set(loader "${CPKT_SYSROOT}/lib/${name}")
if(NOT EXISTS "${loader}")
  set(loader "${CPKT_SYSROOT}/usr/lib/${name}")
endif()
if(NOT EXISTS "${loader}")
  message(FATAL_ERROR "Selected runtime loader is missing")
endif()
set(work "${CPKT_SCRATCH}/loader-test")
file(MAKE_DIRECTORY "${work}")
file(WRITE "${work}/probe.c" "#include <stdio.h>\nint main(void) { return puts(\"selected-loader\") < 0; }\n")
cpkt_test_command("${CPKT_CC}" -std=c89 -pedantic-errors -Werror "${work}/probe.c"
  "-Wl,--dynamic-linker=${loader}" "-Wl,-rpath,${CPKT_SYSROOT}/lib:${CPKT_SYSROOT}/usr/lib" -o "${work}/probe")
cpkt_test_command("${CPKT_READELF}" -l "${work}/probe")
string(FIND "${CPKT_TEST_OUTPUT}" "${loader}" found)
if(found LESS 0)
  message(FATAL_ERROR "Probe does not use the selected interpreter")
endif()
cpkt_test_command(${CPKT_RUNNER} "${work}/probe")
cpkt_test_command(${CPKT_RUNNER} "${loader}" --list "${work}/probe")
string(FIND "${CPKT_TEST_OUTPUT}" "${CPKT_SYSROOT}/" found)
if(found LESS 0)
  message(FATAL_ERROR "Probe did not resolve the selected runtime collection")
endif()
