cmake_minimum_required(VERSION 3.21)
include("${CPKT_ROOT}/tests/test-command.cmake")
set(work "${CPKT_SCRATCH}/sdk-validation")
file(REMOVE_RECURSE "${work}")
set(prefix "${work}/prefix with spaces")
file(MAKE_DIRECTORY "${prefix}/lib/cmake/CpktSDK" "${prefix}/include" "${prefix}/share/cpkt/packages" "${work}/source")
file(COPY_FILE "${CPKT_ROOT}/cmake/CpktSDKValidate.cmake" "${prefix}/lib/cmake/CpktSDK/Validate.cmake")
file(WRITE "${prefix}/include/sample.h" "int sample(void);\n")
file(WRITE "${work}/source/CMakeLists.txt" [=[cmake_minimum_required(VERSION 3.21)
project(sdk_validation NONE)
include("${PREFIX}/lib/cmake/CpktSDK/Validate.cmake")
cpkt_sdk_validate(core)
]=])
set(files "")
foreach(path include/sample.h lib/cmake/CpktSDK/Validate.cmake)
  file(CHMOD "${prefix}/${path}" PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
  file(SHA256 "${prefix}/${path}" sha)
  string(APPEND files "${separator}{\"mode\":\"0644\",\"path\":\"${path}\",\"sha256\":\"${sha}\",\"type\":\"file\"}")
  set(separator ,)
endforeach()
set(before "{\"components\":[],\"files\":[${files}],\"group\":\"core\",\"libc\":\"gnu\",\"macos_deployment_target\":null,")
set(after "\"release_version\":\"1.2.3\",\"requires_core\":null,\"schema_version\":1,\"target_id\":\"x86_64-linux-gnu\"}")
string(SHA256 id "${before}${after}")
set(manifest "${before}\"package_id\":\"${id}\",${after}")
file(WRITE "${prefix}/share/cpkt/packages/core.json" "${manifest}")
set(configure "${CMAKE_COMMAND}" -S "${work}/source" -B "${work}/graph" "-DPREFIX=${prefix}" -DCMAKE_SYSTEM_NAME=Linux)
cpkt_test_command(${configure} -DCPKT_TARGET_ID=x86_64-linux-gnu)
cpkt_test_failure("SDK target mismatch" ${configure} -DCPKT_TARGET_ID=aarch64-linux-gnu)
file(WRITE "${prefix}/include/sample.h" "changed\n")
cpkt_test_failure("SDK payload differs" ${configure} -DCPKT_TARGET_ID=x86_64-linux-gnu)
file(WRITE "${prefix}/include/sample.h" "int sample(void);\n")
cpkt_test_command(${configure} -DCPKT_TARGET_ID=x86_64-linux-gnu)
string(REPLACE "1.2.3" "1.2.4" corrupt "${manifest}")
file(WRITE "${prefix}/share/cpkt/packages/core.json" "${corrupt}")
cpkt_test_failure("manifest identity mismatch" ${configure} -DCPKT_TARGET_ID=x86_64-linux-gnu)
