cmake_minimum_required(VERSION 3.21)
include("${CPKT_ROOT}/tests/test-command.cmake")
set(work "${CPKT_SCRATCH}/verification-scopes")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}/source")
cpkt_test_command(bash "${CPKT_ROOT}/scripts/cpkt-toolchains.sh" discover x86_64-linux-gnu)
if(NOT CPKT_TEST_OUTPUT MATCHES "(^|\n)status=ready(\n|$)")
  message(FATAL_ERROR "Prepare the pinned native compiler before scope tests")
endif()
string(REGEX MATCH "(^|\n)cc=([^\n]+)" found "${CPKT_TEST_OUTPUT}")
set(cc "${CMAKE_MATCH_2}")
string(REGEX MATCH "(^|\n)sysroot=([^\n]+)" found "${CPKT_TEST_OUTPUT}")
set(sysroot "${CMAKE_MATCH_2}")
file(WRITE "${work}/source/library.c" "int sample(void) { return 1; }\n")
foreach(scope host runtime)
  file(WRITE "${work}/source/${scope}.input" pass)
endforeach()
file(WRITE "${work}/source/check.cmake" [=[file(READ "${INPUT}" text)
string(STRIP "${text}" text)
if(NOT text STREQUAL "pass")
  message(FATAL_ERROR "injected failure")
endif()
file(APPEND "${LOG}" "passed\n")
]=])
file(WRITE "${work}/source/CMakeLists.txt" [=[cmake_minimum_required(VERSION 3.21)
project(scopes C)
enable_testing()
include("${CPKT_ROOT}/cmake/CpktMutationPaths.cmake")
include("${CPKT_ROOT}/cmake/CpktVerification.cmake")
add_library(sample STATIC library.c)
foreach(scope host runtime)
  set(command "${CMAKE_COMMAND}" "-DINPUT=${CMAKE_SOURCE_DIR}/${scope}.input"
    "-DLOG=${CMAKE_BINARY_DIR}/${scope}.log" -P "${CMAKE_SOURCE_DIR}/check.cmake")
  add_test(NAME "${scope}" COMMAND ${command})
  set_property(GLOBAL PROPERTY "CPKT_TEST_COMMAND_${scope}" "${command}")
  set_property(GLOBAL PROPERTY "CPKT_TEST_INPUTS_${scope}" "${CMAKE_SOURCE_DIR}/${scope}.input;${CMAKE_SOURCE_DIR}/check.cmake")
endforeach()
set_tests_properties(host PROPERTIES LABELS host-lifecycle)
if(SKIP_CASE)
  set_tests_properties(runtime PROPERTIES SKIP_RETURN_CODE 0)
endif()
cpkt_add_verification_scopes()
]=])
set(graph "${work}/graph")
set(configure "${CMAKE_COMMAND}" -S "${work}/source" -B "${graph}" -G Ninja
  "-DCPKT_ROOT=${CPKT_ROOT}" "-DCMAKE_C_COMPILER=${cc}" "-DCMAKE_SYSROOT=${sysroot}"
  -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY)
cpkt_test_command(${configure})
function(build scope)
  cpkt_test_command("${CMAKE_COMMAND}" --build "${graph}" --target "cpkt_verify_${scope}")
endfunction()
function(counts host runtime)
  foreach(scope host runtime)
    file(STRINGS "${graph}/${scope}.log" lines)
    list(LENGTH lines count)
    if(NOT count EQUAL ${scope})
      message(FATAL_ERROR "Incorrect ${scope} verification count: ${count} != ${${scope}}")
    endif()
  endforeach()
endfunction()
build(host)
build(runtime)
file(SHA256 "${graph}/libsample.a" original)
build(host)
build(runtime)
counts(1 1)
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.05)
file(WRITE "${work}/source/runtime.input" "pass\n")
build(runtime)
counts(1 2)
file(SHA256 "${graph}/libsample.a" unchanged)
if(NOT original STREQUAL unchanged)
  message(FATAL_ERROR "Test input change rebuilt the library")
endif()
file(WRITE "${work}/source/library.c" "int sample(void) { return 2; }\n")
build(runtime)
build(host)
counts(1 3)
file(WRITE "${work}/source/runtime.input" fail)
cpkt_test_failure("injected failure" "${CMAKE_COMMAND}" --build "${graph}" --target cpkt_verify_runtime)
if(EXISTS "${graph}/verification/runtime.passed")
  message(FATAL_ERROR "Failed scope retained its success stamp")
endif()
file(WRITE "${work}/source/runtime.input" pass)
build(runtime)
counts(1 4)
cpkt_test_failure("may not skip" ${configure} -DSKIP_CASE=ON)
