cmake_minimum_required(VERSION 3.21)
include("${CPKT_SOURCE}/cmake/extract-release-archive.cmake")
cpkt_extract_release_archive("${CPKT_ARCHIVE}" "${CPKT_PREFIX}" "cpkt-${CPKT_VERSION}" FALSE)
file(READ "${CPKT_PREFIX}/VERSION" version)
string(STRIP "${version}" version)
if(NOT version STREQUAL CPKT_VERSION)
  message(FATAL_ERROR "Source release version mismatch")
endif()
file(STRINGS "${CPKT_PREFIX}/RELEASE_MANIFEST" manifest)
set(unique "${manifest}")
list(REMOVE_DUPLICATES unique)
file(GLOB_RECURSE files RELATIVE "${CPKT_PREFIX}" LIST_DIRECTORIES FALSE "${CPKT_PREFIX}/*")
list(SORT files)
list(SORT unique)
if(NOT manifest OR NOT files STREQUAL unique)
  message(FATAL_ERROR "Source manifest does not describe the exact extracted inventory")
endif()
list(LENGTH manifest count)
list(LENGTH unique unique_count)
if(NOT count EQUAL unique_count)
  message(FATAL_ERROR "Duplicate source manifest entries")
endif()
foreach(required CMakeLists.txt CMakePresets.json Makefile LICENSE)
  if(NOT required IN_LIST files)
    message(FATAL_ERROR "Missing reconstruction input: ${required}")
  endif()
endforeach()
