file(READ "${LINK_FILE}" link)
foreach(expected IN LISTS CONTAINS)
  string(FIND "${link}" "${expected}" position)
  if(position LESS 0)
    message(FATAL_ERROR "Missing advertised static link closure: ${expected}")
  endif()
endforeach()
foreach(forbidden IN LISTS LACKS)
  string(FIND "${link}" "${forbidden}" position)
  if(NOT position LESS 0)
    message(FATAL_ERROR "Unexpected link dependency: ${forbidden}")
  endif()
endforeach()
