cmake_minimum_required(VERSION 3.21)
if(NOT CPKT_CORE_TARGET MATCHES "^[A-Za-z0-9_-]+$")
  message(FATAL_ERROR "Invalid imported core target")
endif()
if(CPKT_CORE_ACTION STREQUAL "acquire")
  include("${CMAKE_CURRENT_LIST_DIR}/CpktMutationPaths.cmake")
  cpkt_validate_mutation_paths("${CPKT_REPO_ROOT}/build/core-acquisition/${CPKT_CORE_TARGET}/archive-path")
  file(READ "${CPKT_CORE_PIN}" _pin)
  string(JSON _name GET "${_pin}" name)
  string(JSON _url GET "${_pin}" url)
  string(JSON _sha GET "${_pin}" sha256)
  include("${CPKT_REPO_ROOT}/cmake/CpktDependencyArchiveCache.cmake")
  cpkt_initialize_dependency_cache()
  set(CPKT_DEPENDENCY_CACHE_LOCK_TIMEOUT 120)
  cpkt_acquire_dependency_archive(_archive NAME "${_name}" SHA256 "${_sha}" URLS "${_url}")
  file(WRITE "${CPKT_REPO_ROOT}/build/core-acquisition/${CPKT_CORE_TARGET}/archive-path" "${_archive}")
elseif(CPKT_CORE_ACTION STREQUAL "link")
  set(_prefix "${CPKT_REPO_ROOT}/.cache/cpkt/${CPKT_CORE_TARGET}/install")
  file(READ "${CPKT_REPO_ROOT}/cmake/components.json" _inventory)
  string(JSON _count LENGTH "${_inventory}" components)
  math(EXPR _last "${_count} - 1")
  include("${CMAKE_CURRENT_LIST_DIR}/CpktMutationPaths.cmake")
  set(_links "")
  foreach(_index RANGE 0 ${_last})
    string(JSON _name MEMBER "${_inventory}" components ${_index})
    string(JSON _external ERROR_VARIABLE _missing GET "${_inventory}" components "${_name}" external)
    if(_missing OR NOT _external STREQUAL "cpkt")
      continue()
    endif()
    string(JSON _directory GET "${_inventory}" components "${_name}" directory)
    set(_parent "${CPKT_REPO_ROOT}/.cache/deps/${CPKT_CORE_TARGET}/${_directory}")
    set(_link "${_parent}/install")
    cpkt_validate_mutation_paths("${_parent}")
    if(IS_SYMLINK "${_link}")
      file(REAL_PATH "${_link}" _actual)
      if(NOT _actual STREQUAL _prefix)
        message(FATAL_ERROR "Wrong imported core component link: ${_link}")
      endif()
    elseif(EXISTS "${_link}")
      message(FATAL_ERROR "Owned producer output occupies imported core: ${_link}")
    else()
      list(APPEND _links "${_link}")
    endif()
  endforeach()
  foreach(_link IN LISTS _links)
    get_filename_component(_parent "${_link}" DIRECTORY)
    file(MAKE_DIRECTORY "${_parent}")
    file(CREATE_LINK "${_prefix}" "${_link}" SYMBOLIC)
  endforeach()
else()
  message(FATAL_ERROR "Unknown core prerequisite operation")
endif()
