# Native install rules for owned facades and inventory-declared SDK payload.
include("${CMAKE_CURRENT_LIST_DIR}/CpktMutationPaths.cmake")
function(cpkt_register_sdk_install facades)
  string(JSON _package ERROR_VARIABLE _no_package GET "${CPKT_INVENTORY}" groups "${CPKT_GROUP}" package)
  if(_no_package)
    return()
  endif()
  if(NOT CMAKE_BUILD_TYPE STREQUAL "Release")
    return()
  endif()
  cpkt_validate_mutation_paths("${CMAKE_BINARY_DIR}/cpkt-package-components.json"
    "${CMAKE_BINARY_DIR}/cpkt-sdk-install.cmake")
  if(facades)
    install(TARGETS ${facades} ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
  endif()
  include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/CpktPackageMetadata.cmake")
  cpkt_package_component_metadata(_components)
  file(CONFIGURE OUTPUT "${CMAKE_BINARY_DIR}/cpkt-package-components.json" CONTENT "${_components}\n" @ONLY)
  set(CPKT_SDK_CONFIGURED_VALUES "")
  get_cmake_property(_variables CACHE_VARIABLES)
  # Dependency selection may use ordinary variables overriding cache entries.
  list(APPEND _variables CPKT_EXTERNAL_ROOT CPKT_DEPENDENCY_BUILD_ROOT)
  list(REMOVE_DUPLICATES _variables)
  foreach(_variable IN LISTS _variables)
    if(_variable MATCHES "^_CMAKE" OR _variable MATCHES "^CMAKE_(WARN|ERROR)_DEPRECATED$"
        OR _variable STREQUAL "CMAKE_INSTALL_PREFIX")
      continue()
    endif()
    cpkt_literal_argument(_literal "${${_variable}}")
    string(APPEND CPKT_SDK_CONFIGURED_VALUES "set(${_variable} ${_literal})\n")
  endforeach()
  configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/sdk-install.cmake.in"
    "${CMAKE_BINARY_DIR}/cpkt-sdk-install.cmake" @ONLY)
  install(SCRIPT "${CMAKE_BINARY_DIR}/cpkt-sdk-install.cmake")
endfunction()
