# Resolve declarative ownership inside CMake; ExternalProject owns scheduling.
function(cpkt_collect_component name)
  get_property(_visited GLOBAL PROPERTY CPKT_COLLECTED_COMPONENTS)
  if(name IN_LIST _visited)
    return()
  endif()
  get_property(_visiting GLOBAL PROPERTY CPKT_COLLECTING_COMPONENTS)
  if(name IN_LIST _visiting)
    message(FATAL_ERROR "Component dependency cycle: ${name}")
  endif()
  set_property(GLOBAL APPEND PROPERTY CPKT_COLLECTING_COMPONENTS "${name}")
  string(JSON _record ERROR_VARIABLE _missing GET "${CPKT_INVENTORY}" components "${name}")
  if(_missing)
    message(FATAL_ERROR "Unknown component dependency: ${name}")
  endif()
  string(JSON _owner GET "${_record}" group)
  string(JSON _external ERROR_VARIABLE _not_external GET "${_record}" external)
  if(NOT _owner STREQUAL CPKT_GROUP AND NOT (_owner STREQUAL "core" AND _external STREQUAL "cpkt"))
    message(FATAL_ERROR "Forbidden component ownership: ${name}/${_owner}")
  endif()
  string(JSON _count LENGTH "${_record}" dependencies)
  if(_count GREATER 0)
    math(EXPR _last "${_count} - 1")
    foreach(_index RANGE 0 ${_last})
      string(JSON _dependency GET "${_record}" dependencies ${_index})
      cpkt_collect_component("${_dependency}")
    endforeach()
  endif()
  get_property(_visiting GLOBAL PROPERTY CPKT_COLLECTING_COMPONENTS)
  list(REMOVE_ITEM _visiting "${name}")
  set_property(GLOBAL PROPERTY CPKT_COLLECTING_COMPONENTS "${_visiting}")
  set_property(GLOBAL APPEND PROPERTY CPKT_COLLECTED_COMPONENTS "${name}")
endfunction()

function(cpkt_select_components output)
  set_property(GLOBAL PROPERTY CPKT_COLLECTED_COMPONENTS "")
  set_property(GLOBAL PROPERTY CPKT_COLLECTING_COMPONENTS "")
  if(CPKT_DEPENDENCY_PRODUCER AND CPKT_DEPENDENCY)
    cpkt_collect_component("${CPKT_DEPENDENCY}")
    get_property(_selected GLOBAL PROPERTY CPKT_COLLECTED_COMPONENTS)
    set(${output} "${_selected}" PARENT_SCOPE)
    return()
  endif()
  string(JSON _count LENGTH "${CPKT_INVENTORY}" components)
  math(EXPR _last "${_count} - 1")
  foreach(_index RANGE 0 ${_last})
    string(JSON _name MEMBER "${CPKT_INVENTORY}" components ${_index})
    string(JSON _owner GET "${CPKT_INVENTORY}" components "${_name}" group)
    if(_owner STREQUAL CPKT_GROUP)
      cpkt_collect_component("${_name}")
    endif()
  endforeach()
  if(CPKT_BUILD_TESTS)
    string(JSON _tests ERROR_VARIABLE _missing LENGTH "${CPKT_INVENTORY}" groups "${CPKT_GROUP}" test_components)
    if(NOT _missing AND _tests GREATER 0)
      math(EXPR _end "${_tests} - 1")
      foreach(_index RANGE 0 ${_end})
        string(JSON _name GET "${CPKT_INVENTORY}" groups "${CPKT_GROUP}" test_components ${_index})
        cpkt_collect_component("${_name}")
      endforeach()
    endif()
  endif()
  get_property(_selected GLOBAL PROPERTY CPKT_COLLECTED_COMPONENTS)
  set(${output} "${_selected}" PARENT_SCOPE)
endfunction()
