include("${CMAKE_CURRENT_LIST_DIR}/CpktMutationPaths.cmake")

# Small producer settings, not output receipts. Native ExternalProject stamps
# own execution. Inputs are stable during a run; restored state is invalidated
# explicitly. A consumer never refreshes a borrowed component.
function(cpkt_append_lifecycle_owned_dependency_component_root out_paths root root_label component)
  if(root_label STREQUAL "external")
    set(_base "${CMAKE_SOURCE_DIR}/.cache/deps/")
  else()
    set(_base "${CMAKE_SOURCE_DIR}/.cache/deps-build/")
  endif()
  get_filename_component(_root "${root}" ABSOLUTE BASE_DIR "${CMAKE_BINARY_DIR}")
  string(FIND "${_root}" "${_base}" _inside)
  if(NOT _inside EQUAL 0)
    message(FATAL_ERROR "Refuse cleanup outside owned ${component} dependency roots: ${root}")
  endif()
  cpkt_validate_mutation_paths("${_root}")
  set(_paths "${${out_paths}}")
  list(APPEND _paths "${_root}")
  set(${out_paths} "${_paths}" PARENT_SCOPE)
endfunction()


function(cpkt_prepare_dependency_component)
  cmake_parse_arguments(component "" "NAME;BUILD_ROOT;INSTALL_ROOT"
    "VARIABLES;DEPENDS;INPUT_FILES" ${ARGN})
  if(NOT component_NAME IN_LIST CPKT_ACTIVE_COMPONENTS)
    return()
  endif()
  set(_directory "${CPKT_DEPENDENCY_CONTRACT_ROOT}/${CPKT_TARGET_ID}")
  set(_settings "${_directory}/${component_NAME}.inputs")
  set(_complete "${_directory}/${component_NAME}.complete")
  set(_configuration "")
  string(APPEND _configuration "build=${component_BUILD_ROOT}\ninstall=${component_INSTALL_ROOT}\n")
  foreach(_variable IN ITEMS CPKT_TARGET_ID CPKT_TOOLCHAIN_ROOT CMAKE_SYSROOT
      CMAKE_OSX_SYSROOT CMAKE_OSX_DEPLOYMENT_TARGET CPKT_DEPENDENCY_BUILD_TYPE
      CMAKE_C_FLAGS CMAKE_CXX_FLAGS CMAKE_EXE_LINKER_FLAGS
      CMAKE_SHARED_LINKER_FLAGS CMAKE_MODULE_LINKER_FLAGS CMAKE_STATIC_LINKER_FLAGS
      ${component_VARIABLES})
    string(APPEND _configuration "${_variable}=${${_variable}}\n")
  endforeach()
  set(_changed OFF)
  if(EXISTS "${_settings}")
    file(READ "${_settings}" _previous)
    if(NOT _previous STREQUAL _configuration)
      set(_changed ON)
    endif()
    foreach(_input IN LISTS component_INPUT_FILES)
      if(_input MATCHES "CpktDependency(Contract|ArchiveCache)\\.cmake$")
        continue()
      endif()
      if(NOT EXISTS "${_input}" OR "${_input}" IS_NEWER_THAN "${_settings}")
        set(_changed ON)
      endif()
    endforeach()
  endif()
  foreach(_dependency IN LISTS component_DEPENDS)
    get_property(_dependency_changed GLOBAL PROPERTY "CPKT_INPUT_CHANGED_${_dependency}")
    if(_dependency_changed)
      set(_changed ON)
    endif()
  endforeach()
  if(CPKT_DEPENDENCY_PRODUCER)
    cpkt_validate_mutation_paths("${_settings}" "${_complete}")
    if(_changed)
      if(NOT CPKT_EXTERNAL_ROOT_LIFECYCLE_OWNED OR NOT CPKT_DEPENDENCY_BUILD_ROOT_LIFECYCLE_OWNED)
        message(FATAL_ERROR "Changed ${component_NAME} has caller-owned roots; refresh explicitly")
      endif()
      set(_roots "")
      cpkt_append_lifecycle_owned_dependency_component_root(_roots "${component_BUILD_ROOT}" build "${component_NAME}")
      cpkt_append_lifecycle_owned_dependency_component_root(_roots "${component_INSTALL_ROOT}" external "${component_NAME}")
      foreach(_root IN LISTS _roots)
        file(REMOVE_RECURSE "${_root}")
      endforeach()
      file(REMOVE "${_complete}")
    endif()
    if(_changed OR NOT EXISTS "${_settings}")
      file(WRITE "${_settings}" "${_configuration}")
    endif()
  elseif(_changed OR NOT EXISTS "${_settings}" OR NOT EXISTS "${_complete}")
    message(FATAL_ERROR "Missing/stale ${component_NAME} prerequisite; prepare its owning dependency graph first")
  endif()
  set_property(GLOBAL PROPERTY "CPKT_INPUT_CHANGED_${component_NAME}" "${_changed}")
  set_property(GLOBAL PROPERTY "CPKT_COMPONENT_COMPLETE_${component_NAME}" "${_complete}")
endfunction()
