# Validate explicit preflight metadata without selecting or altering toolchains.
if(CPKT_TARGET_ID MATCHES "^(x86_64|aarch64|armhf)-linux-(gnu|musl)$")
  set(_cpkt_expected_arch "${CMAKE_MATCH_1}")
  set(_cpkt_expected_os linux)
  set(_cpkt_expected_libc "${CMAKE_MATCH_2}")
elseif(CPKT_TARGET_ID STREQUAL "arm64-apple-darwin")
  set(_cpkt_expected_arch arm64)
  set(_cpkt_expected_os darwin)
  set(_cpkt_expected_libc "")
else()
  message(FATAL_ERROR "Unsupported preflight target: ${CPKT_TARGET_ID}")
endif()
foreach(_field IN ITEMS ARCH OS LIBC)
  string(TOLOWER "${_field}" _lower)
  if(NOT DEFINED CPKT_TARGET_${_field} OR
      NOT "${CPKT_TARGET_${_field}}" STREQUAL "${_cpkt_expected_${_lower}}")
    message(FATAL_ERROR "Preflight target tuple mismatch: CPKT_TARGET_${_field}='${CPKT_TARGET_${_field}}' for ${CPKT_TARGET_ID}; expected '${_cpkt_expected_${_lower}}'")
  endif()
endforeach()
