# CMake evaluates registration conditions; CTest supplies the executed inventory.
include("${CMAKE_CURRENT_LIST_DIR}/CpktMutationPaths.cmake")
function(cpkt_assert_test_inventory)
  cpkt_validate_mutation_paths("${CMAKE_BINARY_DIR}/cpkt-required-coverage.txt")
  string(JSON _count LENGTH "${CPKT_INVENTORY}" tests)
  math(EXPR _last "${_count} - 1")
  foreach(_index RANGE 0 ${_last})
    if(_count EQUAL 0)
      break()
    endif()
    string(JSON _key MEMBER "${CPKT_INVENTORY}" tests ${_index})
    string(JSON _owner GET "${CPKT_INVENTORY}" tests "${_key}" group)
    if(NOT _owner STREQUAL CPKT_GROUP AND NOT _owner STREQUAL "tooling")
      continue()
    endif()
    if(CPKT_FACADE_ONLY AND CPKT_ENABLE_FUZZING AND CPKT_GROUP STREQUAL "core")
      string(JSON _profile GET "${CPKT_INVENTORY}" groups core profiles lua-fuzz tests)
      string(FIND "${_profile}" "\"${_key}\"" _in_profile)
      if(_in_profile LESS 0)
        continue()
      endif()
    endif()
    string(JSON _registrations ERROR_VARIABLE _missing LENGTH
      "${CPKT_INVENTORY}" tests "${_key}" registrations)
    if(_missing OR _registrations EQUAL 0)
      continue()
    endif()
    math(EXPR _end "${_registrations} - 1")
    foreach(_registration RANGE 0 ${_end})
      string(JSON _name GET "${CPKT_INVENTORY}" tests "${_key}" registrations ${_registration} name)
      string(JSON _conditions LENGTH "${CPKT_INVENTORY}" tests "${_key}" registrations ${_registration} conditions)
      set(_expression TRUE)
      if(_conditions GREATER 0)
        set(_expressions "")
        math(EXPR _condition_end "${_conditions} - 1")
        foreach(_condition_index RANGE 0 ${_condition_end})
          string(JSON _condition GET "${CPKT_INVENTORY}" tests "${_key}" registrations ${_registration} conditions ${_condition_index})
          list(APPEND _expressions "(${_condition})")
        endforeach()
        list(JOIN _expressions " AND " _expression)
      endif()
      set(_check "if(${_expression})\n if(NOT TEST \"${_name}\")\n message(FATAL_ERROR \"Missing required inventory case: ${_name}\")\n endif()\n endif()")
      cmake_language(EVAL CODE "${_check}")
    endforeach()
  endforeach()
  get_property(_tests DIRECTORY PROPERTY TESTS)
  list(JOIN _tests "\n" _coverage)
  file(WRITE "${CMAKE_BINARY_DIR}/cpkt-required-coverage.txt" "${_coverage}\n")
endfunction()
