# Capture the compiled producer's provenance as data for manifest validation.
function(cpkt_json_quote output value)
  string(REPLACE "\\" "\\\\" _value "${value}")
  string(REPLACE "\"" "\\\"" _value "${_value}")
  string(REPLACE "\n" "\\n" _value "${_value}")
  string(REPLACE "\r" "\\r" _value "${_value}")
  string(REPLACE "\t" "\\t" _value "${_value}")
  set(${output} "\"${_value}\"" PARENT_SCOPE)
endfunction()

function(cpkt_package_component_metadata output)
  set(_components "[]")
  set(_component_index 0)
  file(READ "${CMAKE_SOURCE_DIR}/cmake/CpktDependencies.cmake" _recipes)
  file(READ "${CMAKE_SOURCE_DIR}/build/${CPKT_TARGET_ID}/${CPKT_GROUP}/producer/CMakeCache.txt" _producer)
  foreach(_name IN LISTS CPKT_ACTIVE_COMPONENTS)
    string(JSON _record GET "${CPKT_INVENTORY}" components "${_name}")
    string(JSON _owner GET "${_record}" group)
    if(NOT _owner STREQUAL CPKT_GROUP)
      continue()
    endif()
    string(JSON _function_count LENGTH "${_record}" recipe_functions)
    math(EXPR _last "${_function_count} - 1")
    string(JSON _function GET "${_record}" recipe_functions ${_last})
    string(FIND "${_recipes}" "function(${_function}" _start)
    if(_start LESS 0)
      message(FATAL_ERROR "Missing package recipe: ${_function}")
    endif()
    string(SUBSTRING "${_recipes}" ${_start} -1 _tail)
    string(FIND "${_tail}" "endfunction()" _end)
    math(EXPR _length "${_end} + 13")
    string(SUBSTRING "${_tail}" 0 ${_length} _recipe)
    string(SHA256 _recipe_sha "${_recipe}")
    string(REGEX MATCHALL "SHA256=[a-f0-9]+" _digests "${_recipe}")
    list(REMOVE_DUPLICATES _digests)
    if(NOT _digests)
      message(FATAL_ERROR "No pinned package source: ${_name}")
    endif()
    list(GET _digests 0 _primary)
    string(REGEX REPLACE "^SHA256=" "" _primary "${_primary}")
    list(SORT _digests)
    string(JSON _project ERROR_VARIABLE _no_project GET "${_record}" package primary_source_project)
    if(NOT _no_project)
      string(REGEX MATCH "cpkt_cached_external_project_add\\(\\$\\{${_project}\\}[^)]*URL_HASH[ \t\r\n]+\"SHA256=([a-f0-9]+)\"" _match "${_recipe}")
      if(NOT _match)
        message(FATAL_ERROR "Missing primary package source: ${_name}/${_project}")
      endif()
      set(_primary "${CMAKE_MATCH_1}")
    endif()
    string(JSON _version_key GET "${_record}" package version_variable)
    string(REGEX MATCH "(^|\n)${_version_key}:[^=]*=([^\r\n]*)" _match "${_producer}")
    if(NOT _match)
      message(FATAL_ERROR "Missing compiled producer version: ${_name}/${_version_key}")
    endif()
    set(_version "${CMAKE_MATCH_2}")
    set(_metadata "{}")
    foreach(_key name version source_sha256)
      if(_key STREQUAL "name")
        set(_value "${_name}")
      elseif(_key STREQUAL "version")
        set(_value "${_version}")
      else()
        set(_value "${_primary}")
      endif()
      cpkt_json_quote(_quoted "${_value}")
      string(JSON _metadata SET "${_metadata}" "${_key}" "${_quoted}")
    endforeach()
    set(_features "{}")
    string(JSON _variants GET "${_record}" variants)
    string(JSON _features SET "${_features}" variants "${_variants}")
    cpkt_json_quote(_quoted "${_recipe_sha}")
    string(JSON _features SET "${_features}" recipe_sha256 "${_quoted}")
    set(_inputs "{}")
    string(JSON _input_count LENGTH "${_record}" recipe_inputs)
    if(_input_count GREATER 0)
      math(EXPR _last "${_input_count} - 1")
      foreach(_index RANGE 0 ${_last})
        string(JSON _path GET "${_record}" recipe_inputs ${_index})
        file(SHA256 "${CMAKE_SOURCE_DIR}/${_path}" _sha)
        cpkt_json_quote(_quoted "${_sha}")
        string(JSON _inputs SET "${_inputs}" "${_path}" "${_quoted}")
      endforeach()
    endif()
    string(JSON _features SET "${_features}" recipe_inputs "${_inputs}")
    set(_sources "[]")
    set(_source_index 0)
    foreach(_digest IN LISTS _digests)
      string(REGEX REPLACE "^SHA256=" "" _digest "${_digest}")
      cpkt_json_quote(_quoted "${_digest}")
      string(JSON _sources SET "${_sources}" ${_source_index} "${_quoted}")
      math(EXPR _source_index "${_source_index} + 1")
    endforeach()
    string(JSON _features SET "${_features}" source_digests "${_sources}")
    set(_options "{}")
    string(TOUPPER "${_name}" _prefix)
    string(REPLACE "-" "_" _prefix "${_prefix}")
    file(STRINGS "${CMAKE_SOURCE_DIR}/build/${CPKT_TARGET_ID}/${CPKT_GROUP}/producer/CMakeCache.txt" _cache_lines)
    foreach(_line IN LISTS _cache_lines)
      if(_line MATCHES "^(CPKT_${_prefix}_[A-Za-z0-9_]+):[^=]*=(.*)$")
        set(_key "${CMAKE_MATCH_1}")
        set(_value "${CMAKE_MATCH_2}")
        if(NOT _key MATCHES "(PREFIX|DIR|ROOT|LIBRARY)$")
          cpkt_json_quote(_quoted "${_value}")
          string(JSON _options SET "${_options}" "${_key}" "${_quoted}")
        endif()
      endif()
    endforeach()
    string(JSON _features SET "${_features}" options "${_options}")
    string(JSON _facade_count LENGTH "${_record}" package facades)
    if(_facade_count GREATER 0)
      math(EXPR _facade_end "${_facade_count} - 1")
      foreach(_facade_index RANGE 0 ${_facade_end})
        string(JSON _feature_count ERROR_VARIABLE _no_features LENGTH "${_record}" package facades ${_facade_index} features)
        if(_no_features OR _feature_count EQUAL 0)
          continue()
        endif()
        math(EXPR _feature_end "${_feature_count} - 1")
        foreach(_feature_index RANGE 0 ${_feature_end})
          string(JSON _feature MEMBER "${_record}" package facades ${_facade_index} features ${_feature_index})
          string(JSON _variable GET "${_record}" package facades ${_facade_index} features "${_feature}")
          if(NOT DEFINED ${_variable})
            message(FATAL_ERROR "Missing compiled facade feature: ${_name}/${_feature}")
          endif()
          cpkt_json_quote(_quoted "${${_variable}}")
          string(JSON _features SET "${_features}" "${_feature}" "${_quoted}")
        endforeach()
      endforeach()
    endif()
    string(JSON _metadata SET "${_metadata}" features "${_features}")
    string(JSON _metadata SET "${_metadata}" abi "{}")
    string(JSON _components SET "${_components}" ${_component_index} "${_metadata}")
    math(EXPR _component_index "${_component_index} + 1")
  endforeach()
  set(${output} "${_components}" PARENT_SCOPE)
endfunction()
