function(cpkt_apply_auth_export_catalog target_name catalog_name)
  if(NOT TARGET "${target_name}")
    return()
  endif()
  set(_catalog "${CMAKE_SOURCE_DIR}/cmake/exports/${catalog_name}.txt")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_catalog}")
  file(STRINGS "${_catalog}" _symbols REGEX "^cpkt_")
  if(NOT _symbols)
    message(FATAL_ERROR "empty authentication export catalog: ${_catalog}")
  endif()
  if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(_linker_file "${CMAKE_BINARY_DIR}/${catalog_name}.exports")
    set(_linker_contents "")
    foreach(_symbol IN LISTS _symbols)
      string(APPEND _linker_contents "_${_symbol}\n")
    endforeach()
    target_link_options(${target_name} PRIVATE
          "-Wl,-exported_symbols_list,${_linker_file}")
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(_linker_file "${CMAKE_BINARY_DIR}/${catalog_name}.map")
    set(_linker_contents "{\n  global:\n")
    foreach(_symbol IN LISTS _symbols)
      string(APPEND _linker_contents "    ${_symbol};\n")
    endforeach()
    string(APPEND _linker_contents "  local: *;\n};\n")
    target_link_options(${target_name} PRIVATE
          "-Wl,--version-script,${_linker_file}" "-Wl,--exclude-libs,ALL")
  endif()
  if(DEFINED _linker_file)
    include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/CpktMutationPaths.cmake")
    cpkt_register_generated_outputs("${_linker_file}")
    if(EXISTS "${_linker_file}")
      file(READ "${_linker_file}" _previous_linker_contents)
    endif()
    if(NOT "${_previous_linker_contents}" STREQUAL "${_linker_contents}")
      file(WRITE "${_linker_file}" "${_linker_contents}")
    endif()
    set_property(TARGET ${target_name} APPEND PROPERTY LINK_DEPENDS
          "${_linker_file}")
  endif()
endfunction()
