# Compile frozen declarations and public layouts with the selected compiler.
# The snapshots are test expectations, never updated by a build.
function(cpkt_contract_type output type name)
  string(FIND "${type}" "[" array_start)
  if(type MATCHES "^([^()]+) *\\(([^*].*)?\\)$")
    set(declaration "${CMAKE_MATCH_1} ${name}(${CMAKE_MATCH_2})")
  elseif(type MATCHES "\\(\\*\\)")
    string(REPLACE "(*)" "(*${name})" declaration "${type}")
  elseif(NOT array_start LESS 0)
    string(SUBSTRING "${type}" 0 ${array_start} element_type)
    string(SUBSTRING "${type}" ${array_start} -1 dimensions)
    set(declaration "${element_type} ${name}${dimensions}")
  else()
    set(declaration "${type} ${name}")
  endif()
  set(${output} "${declaration}" PARENT_SCOPE)
endfunction()

function(cpkt_contract_declarations content output)
  set(source "")
  foreach(category functions typedefs variables)
    string(JSON count ERROR_VARIABLE missing LENGTH "${content}" "${category}")
    if(missing OR count EQUAL 0)
      continue()
    endif()
    math(EXPR last "${count}-1")
    foreach(index RANGE 0 ${last})
      string(JSON name MEMBER "${content}" "${category}" ${index})
      string(JSON type GET "${content}" "${category}" "${name}")
      if(category STREQUAL "typedefs" AND
          (type STREQUAL "struct ${name}" OR type STREQUAL "enum ${name}"))
        # The frozen extractor names anonymous types after their typedef.
        # There is no matching C tag; fields and enumerators are checked below.
        set(class 1)
        if(type STREQUAL "struct ${name}")
          set(class 12)
        endif()
        string(APPEND source "typedef char check_${name}[sizeof(${name}) > 0 && __builtin_classify_type(*((${name} *)0)) == ${class} ? 1 : -1];\n")
        continue()
      endif()
      if(category STREQUAL "functions")
        cpkt_contract_type(declaration "${type}" "(*expected_${name})")
        set(actual "__typeof__(&${name})")
      elseif(category STREQUAL "variables")
        cpkt_contract_type(declaration "${type}" "expected_${name}")
        set(actual "__typeof__(${name})")
      else()
        cpkt_contract_type(declaration "${type}" "expected_${name}")
        set(actual "${name}")
      endif()
      string(APPEND source "typedef ${declaration};\ntypedef char check_${name}[__builtin_types_compatible_p(${actual}, expected_${name}) ? 1 : -1];\n")
    endforeach()
  endforeach()
  string(JSON count LENGTH "${content}" enums)
  if(count GREATER 0)
    math(EXPR last "${count}-1")
    foreach(index RANGE 0 ${last})
      string(JSON name MEMBER "${content}" enums ${index})
      string(JSON value GET "${content}" enums "${name}")
      string(APPEND source "typedef char check_${name}[${name} == ${value} ? 1 : -1];\n")
    endforeach()
  endif()
  set(${output} "${source}" PARENT_SCOPE)
endfunction()

function(cpkt_contract_members output content)
  string(JSON count LENGTH "${content}" ${ARGN})
  set(names "")
  if(count GREATER 0)
    math(EXPR last "${count}-1")
    foreach(index RANGE 0 ${last})
      string(JSON name MEMBER "${content}" ${ARGN} ${index})
      list(APPEND names "${name}")
    endforeach()
  endif()
  set(${output} "${names}" PARENT_SCOPE)
endfunction()

cpkt_register_generated_outputs("${CMAKE_BINARY_DIR}/generated/contracts/auth_facade.c"
  "${CMAKE_BINARY_DIR}/generated/contracts/auth_gssapi.c"
  "${CMAKE_BINARY_DIR}/generated/contracts/auth_sasl.c")
file(READ "${CMAKE_SOURCE_DIR}/tests/contracts/auth_facade_signatures.json" facade_snapshot)
file(READ "${CMAKE_SOURCE_DIR}/tests/contracts/auth_native_api.json" native_snapshot)
foreach(kind bindings record_bindings variable_bindings constant_bindings)
  file(READ "${CMAKE_SOURCE_DIR}/tests/contracts/auth_${kind}.json" ${kind})
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${CMAKE_SOURCE_DIR}/tests/contracts/auth_${kind}.json")
endforeach()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
  "${CMAKE_SOURCE_DIR}/tests/contracts/auth_facade_signatures.json"
  "${CMAKE_SOURCE_DIR}/tests/contracts/auth_native_api.json")
string(JSON facade GET "${facade_snapshot}" "${CPKT_TARGET_ID}")
cpkt_contract_declarations("${facade}" declarations)
set(source "#include <stddef.h>\n#include <cpkt/gssapi.h>\n#include <cpkt/sasl.h>\n#include <cpkt/sasl_plugin.h>\n${declarations}")
string(JSON count LENGTH "${facade}" records)
math(EXPR last "${count}-1")
foreach(index RANGE 0 ${last})
  string(JSON record MEMBER "${facade}" records ${index})
  string(JSON size GET "${facade}" layouts "${record}" size)
  string(JSON align GET "${facade}" layouts "${record}" align)
  string(APPEND source "typedef char size_${record}[sizeof(struct ${record}) == ${size} ? 1 : -1];\ntypedef char align_${record}[__alignof__(struct ${record}) == ${align} ? 1 : -1];\n")
  string(JSON fields LENGTH "${facade}" layouts "${record}" fields)
  math(EXPR field_last "${fields}-1")
  foreach(field_index RANGE 0 ${field_last})
    string(JSON field GET "${facade}" layouts "${record}" fields ${field_index} 0)
    string(JSON offset GET "${facade}" layouts "${record}" fields ${field_index} 1)
    string(JSON type GET "${facade}" records "${record}" "${field}")
    cpkt_contract_type(declaration "${type}" "expected_field_${record}_${field}")
    string(APPEND source "typedef ${declaration};\ntypedef char field_${record}_${field}[offsetof(struct ${record}, ${field}) == ${offset} && __builtin_types_compatible_p(__typeof__(((struct ${record} *)0)->${field}), expected_field_${record}_${field}) ? 1 : -1];\n")
  endforeach()
endforeach()
string(APPEND source "int main(void) { return 0; }\n")
file(CONFIGURE OUTPUT "${CMAKE_BINARY_DIR}/generated/contracts/auth_facade.c" CONTENT "${source}" @ONLY)
cpkt_group_add_executable(cpkt_auth_facade_contract "${CMAKE_BINARY_DIR}/generated/contracts/auth_facade.c")
target_include_directories(cpkt_auth_facade_contract PRIVATE "${CMAKE_SOURCE_DIR}/include")
target_compile_options(cpkt_auth_facade_contract PRIVATE -std=gnu99 -Werror -Wno-deprecated-declarations)
cpkt_group_use_local_runtime(cpkt_auth_facade_contract)

foreach(provider gssapi sasl)
  file(STRINGS "${CMAKE_SOURCE_DIR}/cmake/exports/cpkt_${provider}.txt" exports)
  string(JSON native GET "${native_snapshot}" "${CPKT_TARGET_ID}" "${provider}")
  cpkt_contract_declarations("${native}" declarations)
  if(provider STREQUAL "gssapi")
    set(includes "#include <gssapi/gssapi.h>\n#include <gssapi/gssapi_ext.h>\n#include <gssapi/gssapi_krb5.h>\n#include <gssapi/gssapi_generic.h>\n#include <gssapi/mechglue.h>\n#include <gssapi/gssapi_alloc.h>\n")
    set(dependency krb5)
  else()
    set(includes "#include <sasl/sasl.h>\n#include <sasl/prop.h>\n#include <sasl/saslutil.h>\n#include <sasl/saslplug.h>\n")
    set(dependency cyrus-sasl)
  endif()
  # Check the binding catalog against the union of the frozen target APIs.
  cpkt_contract_members(targets "${native_snapshot}")
  set(functions "")
  set(macros "")
  foreach(target IN LISTS targets)
    cpkt_contract_members(names "${native_snapshot}" "${target}" "${provider}" functions)
    list(APPEND functions ${names})
    cpkt_contract_members(names "${native_snapshot}" "${target}" "${provider}" macros)
    list(APPEND macros ${names})
  endforeach()
  foreach(category functions macros)
    list(REMOVE_DUPLICATES ${category})
    list(SORT ${category})
  endforeach()
  cpkt_contract_members(mapped "${bindings}" "${provider}")
  list(SORT mapped)
  if(NOT functions STREQUAL mapped)
    message(FATAL_ERROR "Incomplete ${provider} function bindings")
  endif()
  cpkt_contract_members(mapped "${constant_bindings}" "${provider}")
  list(SORT mapped)
  if(NOT macros STREQUAL mapped)
    message(FATAL_ERROR "Incomplete ${provider} constant bindings")
  endif()
  string(APPEND includes "#include <cpkt/gssapi.h>\n#include <cpkt/sasl.h>\n#include <cpkt/sasl_plugin.h>\n")
  foreach(name IN LISTS functions)
    string(JSON entries ERROR_VARIABLE unavailable GET "${bindings}" "${provider}" "${name}" facade)
    if(NOT unavailable)
      string(JSON count LENGTH "${entries}")
      math(EXPR last "${count}-1")
      foreach(index RANGE 0 ${last})
        string(JSON entry GET "${entries}" ${index})
        if(entry MATCHES "^([^.]+)\\.(.+)$")
          string(APPEND declarations "typedef char binding_${name}_${index}[sizeof(((${CMAKE_MATCH_1} *)0)->${CMAKE_MATCH_2}) ? 1 : -1];\n")
        else()
          if(NOT entry IN_LIST exports)
            message(FATAL_ERROR "Binding lacks public export: ${entry}")
          endif()
          string(APPEND declarations "typedef char binding_${name}_${index}[sizeof(&${entry}) ? 1 : -1];\n")
        endif()
      endforeach()
    endif()
  endforeach()
  cpkt_contract_members(records "${native}" records)
  cpkt_contract_members(mapped "${record_bindings}" "${provider}")
  list(SORT records)
  list(SORT mapped)
  if(NOT records STREQUAL mapped)
    message(FATAL_ERROR "Incomplete ${provider} record bindings")
  endif()
  set(check_index 0)
  foreach(record IN LISTS records)
    cpkt_contract_members(fields "${native}" records "${record}")
    cpkt_contract_members(mapped "${record_bindings}" "${provider}" "${record}")
    if(NOT fields STREQUAL mapped)
      message(FATAL_ERROR "Incomplete ${provider} field bindings: ${record}")
    endif()
    foreach(field IN LISTS fields)
      string(JSON kind TYPE "${record_bindings}" "${provider}" "${record}" "${field}")
      if(kind STREQUAL "STRING")
        string(JSON entry GET "${record_bindings}" "${provider}" "${record}" "${field}")
        math(EXPR check_index "${check_index}+1")
        if(entry MATCHES "^([^.]+)\\.(.+)$")
          string(APPEND declarations "typedef char record_binding_${check_index}[sizeof(((${CMAKE_MATCH_1} *)0)->${CMAKE_MATCH_2}) ? 1 : -1];\n")
        else()
          if(NOT entry IN_LIST exports)
            message(FATAL_ERROR "Record binding lacks public export: ${entry}")
          endif()
          string(APPEND declarations "typedef char record_binding_${check_index}[sizeof(&${entry}) ? 1 : -1];\n")
        endif()
      endif()
    endforeach()
    string(REGEX REPLACE "^[^:]+:" "" tag "${record}")
    if(tag MATCHES "^@")
      set(record_type MD5_CTX)
    else()
      set(record_type "struct ${tag}")
    endif()
    string(JSON order_count LENGTH "${native}" record_order "${record}")
    math(EXPR order_last "${order_count}-1")
    set(previous "")
    foreach(index RANGE 0 ${order_last})
      string(JSON field GET "${native}" record_order "${record}" ${index})
      string(JSON type GET "${native}" records "${record}" "${field}")
      math(EXPR check_index "${check_index}+1")
      cpkt_contract_type(declaration "${type}" "expected_field_${check_index}")
      string(APPEND declarations "typedef ${declaration};\ntypedef char native_field_${check_index}[__builtin_types_compatible_p(__typeof__(((${record_type} *)0)->${field}), expected_field_${check_index}) ? 1 : -1];\n")
      if(previous)
        string(APPEND declarations "typedef char native_order_${check_index}[offsetof(${record_type}, ${previous}) < offsetof(${record_type}, ${field}) ? 1 : -1];\n")
      endif()
      set(previous "${field}")
    endforeach()
  endforeach()
  foreach(name IN LISTS macros)
    string(JSON kind ERROR_VARIABLE missing GET "${constant_bindings}" "${provider}" "${name}" kind)
    if(missing OR NOT kind MATCHES "^(numeric|string)$")
      continue()
    endif()
    string(JSON mapped GET "${constant_bindings}" "${provider}" "${name}" facade)
    set(expression "${name}")
    if(name MATCHES "^([^(]+)\\(")
      set(expression "${CMAKE_MATCH_1}(0x10203040UL)")
      string(APPEND mapped "(0x10203040UL)")
    endif()
    math(EXPR check_index "${check_index}+1")
    if(kind STREQUAL "string")
      set(comparison "__builtin_strcmp(${expression}, ${mapped}) == 0")
    else()
      set(comparison "(${expression}) == (${mapped})")
    endif()
    string(APPEND declarations "typedef char constant_binding_${check_index}[${comparison} ? 1 : -1];\n")
  endforeach()
  if(provider STREQUAL "gssapi")
    set(variables "")
    foreach(target IN LISTS targets)
      cpkt_contract_members(names "${native_snapshot}" "${target}" gssapi variables)
      list(APPEND variables ${names})
    endforeach()
    list(REMOVE_DUPLICATES variables)
    list(SORT variables)
    cpkt_contract_members(mapped "${variable_bindings}" gssapi)
    list(SORT mapped)
    if(NOT variables STREQUAL mapped)
      message(FATAL_ERROR "Incomplete GSS public variable bindings")
    endif()
    foreach(name IN LISTS variables)
      string(JSON entry ERROR_VARIABLE unavailable GET "${variable_bindings}" gssapi "${name}" facade)
      if(NOT unavailable)
        if(NOT entry IN_LIST exports)
          message(FATAL_ERROR "GSS variable binding lacks public export: ${entry}")
        endif()
        string(APPEND declarations "typedef char variable_binding_${name}[sizeof(&${entry}) ? 1 : -1];\n")
      endif()
    endforeach()
  else()
    cpkt_contract_members(enums "${native}" enums)
    cpkt_contract_members(mapped "${constant_bindings}" sasl_enums)
    if(NOT enums STREQUAL mapped)
      message(FATAL_ERROR "Incomplete SASL enum bindings")
    endif()
    foreach(name IN LISTS enums)
      string(JSON entry GET "${constant_bindings}" sasl_enums "${name}")
      string(APPEND declarations "typedef char enum_binding_${name}[(int)${name} == (int)${entry} ? 1 : -1];\n")
    endforeach()
  endif()
  file(CONFIGURE OUTPUT "${CMAKE_BINARY_DIR}/generated/contracts/auth_${provider}.c"
    CONTENT "#include <stddef.h>\n${includes}${declarations}int main(void) { return 0; }\n" @ONLY)
  cpkt_group_add_executable(cpkt_auth_${provider}_contract "${CMAKE_BINARY_DIR}/generated/contracts/auth_${provider}.c")
  target_include_directories(cpkt_auth_${provider}_contract PRIVATE
    "${CMAKE_SOURCE_DIR}/include" "${CPKT_EXTERNAL_ROOT}/${dependency}/install/include")
  target_compile_options(cpkt_auth_${provider}_contract PRIVATE -std=gnu99 -Werror -Wno-deprecated-declarations)
  cpkt_group_use_local_runtime(cpkt_auth_${provider}_contract)
endforeach()
