# Native validation of the canonical manifest emitted by the install generator.
# Final artifact fixtures also check exact inventory, modes and binary surfaces.
function(_cpkt_sdk_validate_prefix prefix group)
  set(_cpkt_sdk_prefix "${prefix}" PARENT_SCOPE)
  string(SHA256 key "${prefix};${group}")
  set(_cpkt_sdk_key "${key}" PARENT_SCOPE)
  get_property(_checked GLOBAL PROPERTY "CPKT_VALIDATED_${key}")
  if(_checked)
    return()
  endif()
  set(groups core)
  if(NOT group STREQUAL "core")
    list(APPEND groups "${group}")
  endif()
  set(libraries "")
  foreach(selected IN LISTS groups)
    set(manifest "${prefix}/share/cpkt/packages/${selected}.json")
    if(IS_SYMLINK "${manifest}" OR NOT EXISTS "${manifest}")
      message(FATAL_ERROR "Missing regular SDK manifest: ${manifest}")
    endif()
    file(READ "${manifest}" content)
    string(JSON actual_group GET "${content}" group)
    string(JSON schema GET "${content}" schema_version)
    string(JSON version GET "${content}" release_version)
    string(JSON target GET "${content}" target_id)
    string(JSON id GET "${content}" package_id)
    if(NOT schema EQUAL 1 OR NOT actual_group STREQUAL selected)
      message(FATAL_ERROR "SDK owner mismatch: ${selected}")
    endif()
    string(LENGTH "${id}" id_length)
    if(NOT id_length EQUAL 64 OR NOT id MATCHES "^[a-f0-9]+$"
        OR NOT version MATCHES "^[0-9]+[.][0-9]+[.][0-9]+$")
      message(FATAL_ERROR "Invalid SDK release identity")
    endif()
    string(JSON libc GET "${content}" libc)
    string(JSON floor GET "${content}" macos_deployment_target)
    if(target STREQUAL "arm64-apple-darwin")
      if(NOT libc STREQUAL "" OR NOT floor STREQUAL "15.0")
        message(FATAL_ERROR "Invalid Darwin SDK platform metadata")
      endif()
    elseif(target MATCHES "^(x86_64|aarch64|armhf)-linux-(gnu|musl)$")
      if(NOT libc STREQUAL CMAKE_MATCH_2 OR NOT floor STREQUAL "")
        message(FATAL_ERROR "Invalid Linux SDK platform metadata")
      endif()
    else()
      message(FATAL_ERROR "Unsupported SDK target: ${target}")
    endif()
    if(selected STREQUAL "core")
      string(JSON requirement_type TYPE "${content}" requires_core)
      if(NOT requirement_type STREQUAL "NULL")
        message(FATAL_ERROR "Core SDK must not require an optional package")
      endif()
      set(core "${content}")
    else()
      foreach(field package_id release_version target_id)
        string(JSON expected GET "${content}" requires_core "${field}")
        string(JSON supplied GET "${core}" "${field}")
        if(NOT expected STREQUAL supplied)
          message(FATAL_ERROR "SDK prerequisite mismatch: ${field}")
        endif()
      endforeach()
    endif()
    if(CPKT_TARGET_ID AND NOT target STREQUAL CPKT_TARGET_ID)
      message(FATAL_ERROR "SDK target mismatch: ${target} != ${CPKT_TARGET_ID}")
    endif()
    if(CPKT_EXPECTED_VERSION AND NOT version STREQUAL CPKT_EXPECTED_VERSION)
      message(FATAL_ERROR "SDK release version mismatch")
    endif()
    if(CMAKE_SYSTEM_NAME STREQUAL "Darwin" AND NOT target MATCHES "darwin$")
      message(FATAL_ERROR "Expected a Darwin SDK")
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND NOT target MATCHES "-linux-")
      message(FATAL_ERROR "Expected a Linux SDK")
    endif()
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64)$" AND NOT target MATCHES "^(aarch64|arm64)-")
      message(FATAL_ERROR "SDK architecture mismatch")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(amd64|x86_64)$" AND NOT target MATCHES "^x86_64-")
      message(FATAL_ERROR "SDK architecture mismatch")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm|armhf)$" AND NOT target MATCHES "^armhf-")
      message(FATAL_ERROR "SDK architecture mismatch")
    endif()
    # schema 1 canonical encoding puts this root member before requires_core.
    set(member "\"package_id\":\"${id}\",")
    string(FIND "${content}" "${member}" position)
    if(position LESS 0)
      message(FATAL_ERROR "Noncanonical SDK identity member")
    endif()
    string(LENGTH "${member}" length)
    math(EXPR after "${position}+${length}")
    string(SUBSTRING "${content}" 0 ${position} before)
    string(SUBSTRING "${content}" ${after} -1 after)
    string(SHA256 actual "${before}${after}")
    if(NOT actual STREQUAL id)
      message(FATAL_ERROR "SDK manifest identity mismatch")
    endif()
    string(JSON count LENGTH "${content}" files)
    if(count LESS 1)
      message(FATAL_ERROR "Empty SDK payload inventory")
    endif()
    math(EXPR last "${count}-1")
    set(paths "")
    foreach(index RANGE 0 ${last})
      string(JSON path GET "${content}" files ${index} path)
      if(path STREQUAL "" OR IS_ABSOLUTE "${path}" OR path MATCHES "(^|/)\\.\\.?(/|$)|//|\\\\|/$"
          OR path IN_LIST paths OR path MATCHES "^share/cpkt/packages/")
        message(FATAL_ERROR "Unsafe SDK payload path: ${path}")
      endif()
      list(APPEND paths "${path}")
      set(file "${prefix}/${path}")
      get_filename_component(parent "${file}" DIRECTORY)
      while(NOT parent STREQUAL prefix)
        if(IS_SYMLINK "${parent}")
          message(FATAL_ERROR "SDK payload beneath a symlink: ${path}")
        endif()
        get_filename_component(parent "${parent}" DIRECTORY)
      endwhile()
      string(JSON type GET "${content}" files ${index} type)
      if(type STREQUAL "symlink")
        if(NOT IS_SYMLINK "${file}" OR NOT EXISTS "${file}")
          message(FATAL_ERROR "Missing SDK link: ${path}")
        endif()
        file(READ_SYMLINK "${file}" actual)
        string(JSON expected GET "${content}" files ${index} target)
        file(REAL_PATH "${file}" resolved)
        file(RELATIVE_PATH relative "${prefix}" "${resolved}")
        if(IS_ABSOLUTE "${actual}" OR relative MATCHES "^\\.\\./" OR IS_ABSOLUTE "${relative}")
          message(FATAL_ERROR "Escaping SDK link: ${path}")
        endif()
        list(APPEND link_targets "${relative}")
      elseif(type STREQUAL "file")
        if(IS_SYMLINK "${file}" OR IS_DIRECTORY "${file}" OR NOT EXISTS "${file}")
          message(FATAL_ERROR "Missing regular SDK file: ${path}")
        endif()
        file(SHA256 "${file}" actual)
        string(JSON expected GET "${content}" files ${index} sha256)
        string(JSON expected_mode GET "${content}" files ${index} mode)
        if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
          execute_process(COMMAND stat -f %Lp "${file}" RESULT_VARIABLE result OUTPUT_VARIABLE mode)
        else()
          execute_process(COMMAND stat -c %a "${file}" RESULT_VARIABLE result OUTPUT_VARIABLE mode)
        endif()
        string(STRIP "${mode}" mode)
        string(REGEX REPLACE "^0+" "" expected_mode "${expected_mode}")
        if(NOT result EQUAL 0 OR NOT mode STREQUAL expected_mode)
          message(FATAL_ERROR "SDK payload mode mismatch: ${path}")
        endif()
      else()
        message(FATAL_ERROR "Unsupported SDK file type: ${type}")
      endif()
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "SDK payload differs from its manifest: ${path}")
      endif()
      if(path MATCHES "^lib/[^/]+\\.(a|so|dylib|[0-9.]+dylib)")
        get_filename_component(name "${path}" NAME)
        list(APPEND libraries "${name}")
      endif()
    endforeach()
    list(APPEND owned ${paths} "share/cpkt/packages/${selected}.json")
  endforeach()
  foreach(relative IN LISTS link_targets)
    if(NOT relative IN_LIST owned)
      message(FATAL_ERROR "SDK link reaches an unselected payload: ${relative}")
    endif()
  endforeach()
  set_property(GLOBAL PROPERTY "CPKT_PAYLOAD_PATHS_${key}" "${owned}")
  set_property(GLOBAL PROPERTY "CPKT_LIBRARY_NAMES_${key}" "${libraries}")
  set_property(GLOBAL PROPERTY "CPKT_VALIDATED_${key}" TRUE)
endfunction()

function(cpkt_sdk_validate group)
  get_filename_component(prefix "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../.." REALPATH)
  _cpkt_sdk_validate_prefix("${prefix}" "${group}")
  set(_cpkt_sdk_prefix "${prefix}" PARENT_SCOPE)
  set(_cpkt_sdk_key "${_cpkt_sdk_key}" PARENT_SCOPE)
endfunction()

# Imported GLOBAL targets created in a sibling directory are visible to this
# consumer, but CMake lists them only in their defining directory.
function(cpkt_sdk_global_imports directory output)
  get_property(imports DIRECTORY "${directory}" PROPERTY IMPORTED_TARGETS)
  set(result "")
  foreach(target IN LISTS imports)
    if(TARGET "${target}")
      get_target_property(is_global "${target}" IMPORTED_GLOBAL)
      if(is_global)
        list(APPEND result "${target}")
      endif()
    endif()
  endforeach()
  get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(child IN LISTS children)
    cpkt_sdk_global_imports("${child}" nested)
    list(APPEND result ${nested})
  endforeach()
  set(${output} "${result}" PARENT_SCOPE)
endfunction()

# Reject pre-existing host imports of libraries in the selected SDK closure.
function(cpkt_sdk_assert_targets group)
  get_filename_component(prefix "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../.." REALPATH)
  cpkt_sdk_validate("${group}")
  get_property(libraries GLOBAL PROPERTY "CPKT_LIBRARY_NAMES_${_cpkt_sdk_key}")
  set(directory "${CMAKE_CURRENT_SOURCE_DIR}")
  set(imports "")
  while(directory)
    get_property(targets DIRECTORY "${directory}" PROPERTY IMPORTED_TARGETS)
    list(APPEND imports ${targets})
    get_property(directory DIRECTORY "${directory}" PROPERTY PARENT_DIRECTORY)
  endwhile()
  cpkt_sdk_global_imports("${CMAKE_SOURCE_DIR}" global_imports)
  list(APPEND imports ${global_imports})
  list(REMOVE_DUPLICATES imports)
  foreach(target IN LISTS imports)
      get_target_property(configurations "${target}" IMPORTED_CONFIGURATIONS)
      set(properties IMPORTED_LOCATION IMPORTED_IMPLIB INTERFACE_LINK_LIBRARIES)
      foreach(configuration IN LISTS configurations)
        string(TOUPPER "${configuration}" configuration)
        list(APPEND properties "IMPORTED_LOCATION_${configuration}" "IMPORTED_IMPLIB_${configuration}")
      endforeach()
      foreach(property IN LISTS properties)
        get_target_property(location "${target}" "${property}")
        set(locations "")
        foreach(value IN LISTS location)
          if(IS_ABSOLUTE "${value}")
            # A literal comma belongs to a normal path, not a genex delimiter.
            list(APPEND locations "${value}")
          else()
            string(REGEX MATCHALL "/[^;,<>]+" generated_locations "${value}")
            list(APPEND locations ${generated_locations})
          endif()
        endforeach()
        foreach(location IN LISTS locations)
          get_filename_component(name "${location}" NAME)
          if(name IN_LIST libraries)
            file(RELATIVE_PATH relative "${prefix}" "${location}")
            if(relative MATCHES "^[.][.]/" OR IS_ABSOLUTE "${relative}")
              message(FATAL_ERROR "Existing target ${target} imports SDK library ${name} from outside validated prefix: ${location}")
            endif()
          endif()
        endforeach()
      endforeach()
  endforeach()
endfunction()
