include_guard(GLOBAL)
# Validate raw mutation paths, including missing/dangling leaves, before use.
# Reads of imported SDKs and caller-owned dependency roots are independent.
function(cpkt_validate_mutation_paths)
  foreach(_path IN LISTS ARGN)
    if(NOT IS_ABSOLUTE "${_path}")
      message(FATAL_ERROR "Mutation path must be absolute: ${_path}")
    endif()
    set(_parent "${_path}")
    while(TRUE)
      if(IS_SYMLINK "${_parent}")
        message(FATAL_ERROR "Mutation path has a symlink ancestor: ${_parent}")
      endif()
      get_filename_component(_next "${_parent}" DIRECTORY)
      if(_next STREQUAL _parent)
        break()
      endif()
      set(_parent "${_next}")
    endwhile()
  endforeach()
endfunction()
