# Validate the project's deterministic GNU tar layout before extracting it.
# Release members use normalized POSIX names without newlines or semicolons.
include("${CMAKE_CURRENT_LIST_DIR}/gnu_tar.cmake")
function(cpkt_extract_release_archive archive destination root allow_links)
  cpkt_find_gnu_tar(tar)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env LC_ALL=C TZ=UTC
    "${tar}" --list --verbose --numeric-owner --full-time -f "${archive}"
    RESULT_VARIABLE result OUTPUT_VARIABLE listing ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot read release archive: ${error}")
  endif()
  string(REPLACE "\n" ";" records "${listing}")
  set(names "")
  set(links "")
  foreach(record IN LISTS records)
    if(record STREQUAL "")
      continue()
    endif()
    if(NOT record MATCHES "^([-dl][rwx-]+)[ \t]+0/0[ \t]+[0-9]+[ \t]+1970-01-01 00:00:00[ \t]+(.+)$")
      message(FATAL_ERROR "Unsupported or nondeterministic archive entry: ${record}")
    endif()
    set(mode "${CMAKE_MATCH_1}")
    set(name "${CMAKE_MATCH_2}")
    if(mode MATCHES "^l")
      if(NOT allow_links OR NOT name MATCHES "^(.+) -> (.+)$")
        message(FATAL_ERROR "Unsupported archive link: ${name}")
      endif()
      set(name "${CMAKE_MATCH_1}")
      set(link "${CMAKE_MATCH_2}")
      if(IS_ABSOLUTE "${link}")
        message(FATAL_ERROR "Absolute archive link: ${name}")
      endif()
      get_filename_component(parent "${name}" DIRECTORY)
      cmake_path(SET resolved NORMALIZE "${parent}/${link}")
      string(FIND "${resolved}" "${root}/" in_root)
      if(NOT in_root EQUAL 0)
        message(FATAL_ERROR "Escaping archive link: ${name}")
      endif()
      list(APPEND links "${name}")
    endif()
    string(REGEX REPLACE "/$" "" name "${name}")
    string(FIND "${name}" "${root}/" in_root)
    if(NOT (name STREQUAL root OR in_root EQUAL 0)
        OR name MATCHES "(^|/)\\.\\.?(/|$)|//|\\\\" OR name IN_LIST names)
      message(FATAL_ERROR "Unsafe or duplicate archive member: ${name}")
    endif()
    list(APPEND names "${name}")
  endforeach()
  if(NOT names)
    message(FATAL_ERROR "Empty release archive")
  endif()
  foreach(name IN LISTS names)
    get_filename_component(parent "${name}" DIRECTORY)
    while(parent)
      if(parent IN_LIST links)
        message(FATAL_ERROR "Archive member beneath a symlink: ${name}")
      endif()
      get_filename_component(parent "${parent}" DIRECTORY)
    endwhile()
  endforeach()
  if(IS_SYMLINK "${destination}")
    message(FATAL_ERROR "Redirected extraction directory: ${destination}")
  endif()
  file(REMOVE_RECURSE "${destination}")
  file(MAKE_DIRECTORY "${destination}")
  execute_process(COMMAND "${tar}" --extract --gzip --no-same-owner --same-permissions
    --strip-components=1 -f "${archive}" -C "${destination}"
    RESULT_VARIABLE result ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Release extraction failed: ${error}")
  endif()
endfunction()
