cmake_minimum_required(VERSION 3.21)
if(NOT CPKT_REPO_ROOT)
  get_filename_component(CPKT_REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
file(READ "${CPKT_REPO_ROOT}/cmake/components.json" _inventory)
string(JSON _owner GET "${_inventory}" repository_group)
if(CPKT_INFO STREQUAL "owner")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${_owner}")
elseif(CPKT_INFO STREQUAL "abi-defaults")
  include("${CPKT_REPO_ROOT}/cmake/CpktABIVersions.cmake")
  include("${CPKT_REPO_ROOT}/cmake/CpktPackageMetadata.cmake")
  string(JSON _count LENGTH "${_inventory}" components)
  math(EXPR _last "${_count} - 1")
  set(_result "{}")
  foreach(_index RANGE 0 ${_last})
    string(JSON _name MEMBER "${_inventory}" components ${_index})
    string(JSON _group GET "${_inventory}" components "${_name}" group)
    if(NOT _group STREQUAL _owner)
      continue()
    endif()
    string(JSON _facades LENGTH "${_inventory}" components "${_name}" package facades)
    if(_facades EQUAL 0)
      continue()
    endif()
    math(EXPR _end "${_facades} - 1")
    foreach(_facade RANGE 0 ${_end})
      string(JSON _key ERROR_VARIABLE _missing GET "${_inventory}" components "${_name}" package facades ${_facade} abi_version_variable)
      if(NOT _missing)
        cpkt_json_quote(_quoted "${${_key}}")
        string(JSON _result SET "${_result}" "${_key}" "${_quoted}")
      endif()
    endforeach()
  endforeach()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${_result}")
elseif(CPKT_INFO STREQUAL "examples")
  string(JSON _tests LENGTH "${_inventory}" tests)
  math(EXPR _last "${_tests} - 1")
  set(_examples OFF)
  foreach(_index RANGE 0 ${_last})
    if(_tests EQUAL 0)
      break()
    endif()
    string(JSON _name MEMBER "${_inventory}" tests ${_index})
    string(JSON _group GET "${_inventory}" tests "${_name}" group)
    if(_group STREQUAL _owner AND _name MATCHES "example")
      set(_examples ON)
    endif()
  endforeach()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${_examples}")
elseif(CPKT_INFO STREQUAL "targets")
  string(JSON _count LENGTH "${_inventory}" package_targets)
  math(EXPR _last "${_count} - 1")
  foreach(_index RANGE 0 ${_last})
    string(JSON _target GET "${_inventory}" package_targets ${_index})
    execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${_target}")
  endforeach()
elseif(CPKT_INFO STREQUAL "components")
  string(JSON _count LENGTH "${_inventory}" components)
  math(EXPR _last "${_count} - 1")
  foreach(_index RANGE 0 ${_last})
    string(JSON _name MEMBER "${_inventory}" components ${_index})
    string(JSON _group GET "${_inventory}" components "${_name}" group)
    if(_group STREQUAL _owner)
      execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${_name}")
    endif()
  endforeach()
elseif(CPKT_INFO STREQUAL "dependency")
  string(JSON _group ERROR_VARIABLE _error GET "${_inventory}" components "${CPKT_DEPENDENCY}" group)
  if(_error OR NOT _group STREQUAL _owner)
    message(FATAL_ERROR "Dependency ${CPKT_DEPENDENCY} is not owned by ${_owner}")
  endif()
elseif(CPKT_INFO STREQUAL "component-directory")
  string(JSON _directory GET "${_inventory}" components "${CPKT_DEPENDENCY}" directory)
  string(JSON _group GET "${_inventory}" components "${CPKT_DEPENDENCY}" group)
  if(NOT _group STREQUAL _owner)
    message(FATAL_ERROR "Cannot clean a borrowed component: ${CPKT_DEPENDENCY}")
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${_directory}")
elseif(CPKT_INFO STREQUAL "memcheck-suppression")
  string(JSON _suppression ERROR_VARIABLE _missing GET "${_inventory}" groups "${_owner}" hardening memcheck_suppression)
  if(NOT _missing)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${_suppression}")
  endif()
elseif(CPKT_INFO STREQUAL "target")
  include("${CPKT_REPO_ROOT}/cmake/CpktGroups.cmake")
  cpkt_inventory_owner(targets "${CPKT_TARGET}" _group)
  if(NOT _group STREQUAL _owner AND NOT _group STREQUAL "tooling")
    message(FATAL_ERROR "Target ${CPKT_TARGET} is not owned by ${_owner}")
  endif()
else()
  message(FATAL_ERROR "Unknown lifecycle information request: ${CPKT_INFO}")
endif()
