cmake_minimum_required(VERSION 3.21)
set(CTEST_SOURCE_DIRECTORY "${CPKT_SOURCE}")
set(CTEST_BINARY_DIRECTORY "${CPKT_BINARY}")
set(CTEST_SITE local)
set(CTEST_BUILD_NAME cpkt-native)
find_program(CTEST_MEMORYCHECK_COMMAND valgrind REQUIRED)
set(CTEST_MEMORYCHECK_COMMAND_OPTIONS
  "--error-exitcode=1 --leak-check=full --track-origins=yes --show-leak-kinds=definite,indirect")
set(CTEST_MEMORYCHECK_SUPPRESSIONS_FILE "${CPKT_SUPPRESSIONS}")
file(STRINGS "${CPKT_BINARY}/verification/memcheck.names" names)
if(CPKT_REGEX)
  list(FILTER names INCLUDE REGEX "${CPKT_REGEX}")
endif()
if(NOT names)
  message(FATAL_ERROR "No required memory checks selected")
endif()
ctest_start(Experimental)
ctest_memcheck(BUILD "${CPKT_BINARY}" INCLUDE_LABEL memcheck INCLUDE "${CPKT_REGEX}"
  STOP_ON_FAILURE RETURN_VALUE result DEFECT_COUNT defects)
if(NOT result EQUAL 0 OR NOT defects EQUAL 0)
  message(FATAL_ERROR "Memory checks failed: result=${result}, defects=${defects}")
endif()
