if(NOT DEFINED CPKT_LUA_SOURCE_DIR OR NOT DEFINED CPKT_LUA_HOOK_POLICY_HEADER)
  message(FATAL_ERROR "Lua runtime hook patch requires source and policy header")
endif()
set(_source "${CPKT_LUA_SOURCE_DIR}/src/lgc.c")
file(READ "${_source}" _text)
set(_original "    L->allowhook = 0;  /* stop debug hooks during GC metamethod */")
set(_patched "    /* cpkt runtime limits also account for Lua finalizer instructions. */\n    L->allowhook = (L->hookmask & CPKT_LUA_RUNTIME_MASK_FINALIZERS) ? 1 : 0;")
string(FIND "${_text}" "${_patched}" _already)
if(_already EQUAL -1)
  string(FIND "${_text}" "${_original}" _found)
  if(_found EQUAL -1)
    message(FATAL_ERROR "Unsupported Lua GC implementation for runtime hook patch")
  endif()
  string(REPLACE "${_original}" "${_patched}" _text "${_text}")
  string(REPLACE "#include \"lstate.h\"" "#include \"lstate.h\"\n#include \"cpkt_lua_runtime_hook_policy.h\"" _text "${_text}")
  file(WRITE "${_source}" "${_text}")
endif()
file(COPY_FILE "${CPKT_LUA_HOOK_POLICY_HEADER}"
  "${CPKT_LUA_SOURCE_DIR}/src/cpkt_lua_runtime_hook_policy.h" ONLY_IF_DIFFERENT)
