# Complete the native discovery names, then bind all metadata to this SDK prefix.
if(CPKT_TARGET_ID MATCHES "darwin$")
  set(_shared_suffix ".dylib")
else()
  set(_shared_suffix ".so")
endif()
if(_owner STREQUAL "core")
  set(_native "${_stage_root}/lib/cmake/cmocka")
  file(MAKE_DIRECTORY "${_native}" "${_stage_root}/lib/cmake/CpktCmocka")
  set(_cmocka_config [=[
get_filename_component(_cpkt_cmocka_prefix "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
foreach(v static shared)
  if(v STREQUAL "static")
    set(suffix ".a")
  else()
    set(suffix "@_shared_suffix@")
  endif()
  string(TOUPPER "${v}" type)
  if(NOT TARGET cpkt::cmocka_${v})
    add_library(cpkt::cmocka_${v} ${type} IMPORTED)
    set_target_properties(cpkt::cmocka_${v} PROPERTIES IMPORTED_LOCATION "${_cpkt_cmocka_prefix}/lib/libcmocka${suffix}" INTERFACE_INCLUDE_DIRECTORIES "${_cpkt_cmocka_prefix}/include")
    if(v STREQUAL "static")
      set_property(TARGET cpkt::cmocka_static PROPERTY INTERFACE_COMPILE_DEFINITIONS CMOCKA_STATIC)
      set_property(TARGET cpkt::cmocka_static PROPERTY INTERFACE_LINK_LIBRARIES m)
    endif()
  endif()
endforeach()
if(NOT TARGET cmocka::cmocka)
  add_library(cmocka::cmocka ALIAS cpkt::cmocka_shared)
endif()
set(CMOCKA_LIBRARY cmocka::cmocka)
set(CMOCKA_LIBRARIES cmocka::cmocka)
]=])
  string(CONFIGURE "${_cmocka_config}" _cmocka_config @ONLY)
  file(WRITE "${_native}/cmocka-config.cmake" "${_cmocka_config}")
  set(_facade_config [=[
include(CMakeFindDependencyMacro)
find_dependency(cmocka CONFIG REQUIRED)
get_filename_component(_cpkt_cmocka_prefix "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
foreach(v static shared)
  if(v STREQUAL "static")
    set(suffix ".a")
  else()
    set(suffix "@_shared_suffix@")
  endif()
  string(TOUPPER "${v}" type)
  if(NOT TARGET cpkt::cmocka_facade_${v})
    add_library(cpkt::cmocka_facade_${v} ${type} IMPORTED)
    set_target_properties(cpkt::cmocka_facade_${v} PROPERTIES IMPORTED_LOCATION "${_cpkt_cmocka_prefix}/lib/libcpkt_cmocka${suffix}" INTERFACE_INCLUDE_DIRECTORIES "${_cpkt_cmocka_prefix}/include" INTERFACE_LINK_LIBRARIES "cpkt::cmocka_${v};m")
  endif()
endforeach()
]=])
  string(CONFIGURE "${_facade_config}" _facade_config @ONLY)
  file(WRITE "${_stage_root}/lib/cmake/CpktCmocka/CpktCmockaConfig.cmake" "${_facade_config}")
  include(CMakePackageConfigHelpers)
  write_basic_package_version_file("${_native}/cmocka-config-version.cmake" VERSION "${CPKT_CMOCKA_VERSION}" COMPATIBILITY AnyNewerVersion)
  write_basic_package_version_file("${_stage_root}/lib/cmake/CpktCmocka/CpktCmockaConfigVersion.cmake" VERSION "${CPKT_BUNDLE_VERSION}" COMPATIBILITY AnyNewerVersion)
  foreach(_name cmocka cmocka-shared cmocka-static cpkt-cmocka)
    set(_libs "-lcmocka")
    set(_flags "")
    set(_requires "")
    set(_version "${CPKT_CMOCKA_VERSION}")
    if(_name STREQUAL "cmocka-static")
      set(_libs "\${libdir}/libcmocka.a")
      set(_flags "-DCMOCKA_STATIC")
    elseif(_name STREQUAL "cpkt-cmocka")
      set(_libs "-lcpkt_cmocka")
      set(_requires "Requires: cmocka\n")
      set(_version "${CPKT_BUNDLE_VERSION}")
    endif()
    file(WRITE "${_stage_root}/lib/pkgconfig/${_name}.pc"
      "prefix=\${pcfiledir}/../..\nlibdir=\${prefix}/lib\nincludedir=\${prefix}/include\nName: ${_name}\nDescription: cmocka native/C89 test SDK\nVersion: ${_version}\nLibs: -L\${libdir} ${_libs}\nLibs.private: -lm\nCflags: -I\${includedir} ${_flags}\n${_requires}")
  endforeach()
  file(WRITE "${_stage_root}/lib/pkgconfig/cpkt-core.pc"
    "prefix=\${pcfiledir}/../..\nName: cpkt-core\nDescription: Validated cpkt core identity marker\nVersion: ${CPKT_BUNDLE_VERSION}\nLibs:\nCflags:\n")
  set(_core_version "${CPKT_BUNDLE_VERSION}")
else()
  file(READ "${CPKT_SOURCE_DIR}/.cache/cpkt/${CPKT_TARGET_ID}/install/share/cpkt/packages/core.json" _core)
  string(JSON _core_version GET "${_core}" release_version)
endif()

file(GLOB_RECURSE _configs "${_stage_root}/lib/cmake/*.cmake")
set(_validation_preamble [=[include("${CMAKE_CURRENT_LIST_DIR}/../CpktSDK/Validate.cmake")
cpkt_sdk_validate(@_owner@)
cpkt_sdk_assert_targets(@_owner@)
]=])
string(CONFIGURE "${_validation_preamble}" _validation_preamble @ONLY)
foreach(_config IN LISTS _configs)
  file(READ "${_config}" _content)
  string(REGEX REPLACE "find_dependency\\(([^ \t\r\n)]+)([^)]*CONFIG[^)]*)\\)"
    "find_dependency(\\1\\2 PATHS \"\${_cpkt_sdk_prefix}\" NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)" _content "${_content}")
  if(_config MATCHES "(Config|config)[.]cmake$" AND NOT _config MATCHES "(ConfigVersion|config-version)[.]cmake$")
    string(PREPEND _content "${_validation_preamble}")
    string(APPEND _content "\ncpkt_sdk_assert_targets(${_owner})\n")
  endif()
  file(WRITE "${_config}" "${_content}")
endforeach()
file(GLOB _pcs "${_stage_root}/lib/pkgconfig/*.pc")
foreach(_pc IN LISTS _pcs)
  if(_pc MATCHES "/cpkt-core[.]pc$")
    continue()
  endif()
  file(READ "${_pc}" _content)
  if(_content MATCHES "(^|\n)Requires:([^\n]*)")
    string(REGEX REPLACE "(^|\n)Requires:([^\n]*)" "\\1Requires:\\2, cpkt-core = ${_core_version}" _content "${_content}")
  else()
    string(APPEND _content "Requires: cpkt-core = ${_core_version}\n")
  endif()
  file(WRITE "${_pc}" "${_content}")
endforeach()
