cmake_minimum_required(VERSION 3.21)
foreach(_required IN ITEMS CPKT_REPO_ROOT CPKT_TARGET_ID CPKT_COMPONENT)
  if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
    message(FATAL_ERROR "Missing ${_required}")
  endif()
endforeach()
set(CMAKE_SOURCE_DIR "${CPKT_REPO_ROOT}")
include("${CPKT_REPO_ROOT}/cmake/CpktDependencyContract.cmake")
cpkt_validate_saved_dependency_contract("${CPKT_REPO_ROOT}" "${CPKT_TARGET_ID}" "${CPKT_COMPONENT}")
