cmake_minimum_required(VERSION 3.21)
file(STRINGS "${CPKT_MANIFEST}" lines)
set(found "")
foreach(line IN LISTS lines)
  if(NOT line MATCHES "^([a-f0-9]+)  (.+)$")
    message(FATAL_ERROR "Invalid checksum entry: ${line}")
  endif()
  set(expected "${CMAKE_MATCH_1}")
  set(name "${CMAKE_MATCH_2}")
  string(LENGTH "${expected}" length)
  if(NOT length EQUAL 64 OR NOT name IN_LIST CPKT_FILES OR name IN_LIST found)
    message(FATAL_ERROR "Unexpected/duplicate artifact: ${name}")
  endif()
  file(SHA256 "${CPKT_BASE}/${name}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Checksum mismatch: ${name}")
  endif()
  list(APPEND found "${name}")
endforeach()
list(SORT found)
list(SORT CPKT_FILES)
if(NOT found STREQUAL CPKT_FILES)
  message(FATAL_ERROR "Incomplete artifact manifest")
endif()
file(GLOB existing RELATIVE "${CPKT_BASE}" "${CPKT_BASE}/cpkt-*.tar.gz" "${CPKT_BASE}/cpkt-*.zip")
foreach(name IN LISTS existing)
  if(NOT name IN_LIST CPKT_FILES)
    message(FATAL_ERROR "Stale/unlisted release-looking artifact: ${name}")
  endif()
endforeach()
